name: Feature request
description: Suggest an idea for this project
labels: [ "enhancement" ]
assignees: [ ]

body:
  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: "A clear and concise description of what the use-case is. This will better help us understand the context in which you're looking for a new feature."
    validations:
      required: true
  - type: textarea
    id: desired-solution
    attributes:
      label: Describe the solution you'd like
      description: "A clear and concise description of what you want to happen."
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: "A clear and concise description of any alternative solutions or features you've considered."
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: "Add any other context or screenshots about the feature request here."
  - type: markdown
    attributes:
      value: "Thanks for suggesting a feature! We appreciate your feedback and will consider it for future enhancements."
