package tools.jackson.module.kotlin.kogeraIntegration.deser.valueClass.parameterSize.nonNullObject

import tools.jackson.module.kotlin.assertReflectEquals
import tools.jackson.module.kotlin.defaultMapper
import tools.jackson.module.kotlin.readValue
import tools.jackson.module.kotlin.kogeraIntegration.deser.valueClass.NonNullObject
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.assertThrows
import kotlin.reflect.jvm.internal.KotlinReflectionInternalError
import org.junit.jupiter.api.Test

/**
 * Up to argument size 32 there is one mask argument for the default argument,
 * 33 ~ 64 there are two, and 65 there are three, so each boundary value is tested.
 * Also, if the default argument is set, the maximum argument size that can be set in the constructor is 245,
 * so that case is tested as well.
 */
class DeserializeByConstructorWithDefaultArgumentsTest {
    data class Dst32(
        val p00: NonNullObject = NonNullObject("0"),
        val p01: NonNullObject = NonNullObject("1"),
        val p02: NonNullObject = NonNullObject("2"),
        val p03: NonNullObject = NonNullObject("3"),
        val p04: NonNullObject = NonNullObject("4"),
        val p05: NonNullObject = NonNullObject("5"),
        val p06: NonNullObject = NonNullObject("6"),
        val p07: NonNullObject = NonNullObject("7"),
        val p08: NonNullObject = NonNullObject("8"),
        val p09: NonNullObject = NonNullObject("9"),
        val p10: NonNullObject = NonNullObject("10"),
        val p11: NonNullObject = NonNullObject("11"),
        val p12: NonNullObject = NonNullObject("12"),
        val p13: NonNullObject = NonNullObject("13"),
        val p14: NonNullObject = NonNullObject("14"),
        val p15: NonNullObject = NonNullObject("15"),
        val p16: NonNullObject = NonNullObject("16"),
        val p17: NonNullObject = NonNullObject("17"),
        val p18: NonNullObject = NonNullObject("18"),
        val p19: NonNullObject = NonNullObject("19"),
        val p20: NonNullObject = NonNullObject("20"),
        val p21: NonNullObject = NonNullObject("21"),
        val p22: NonNullObject = NonNullObject("22"),
        val p23: NonNullObject = NonNullObject("23"),
        val p24: NonNullObject = NonNullObject("24"),
        val p25: NonNullObject = NonNullObject("25"),
        val p26: NonNullObject = NonNullObject("26"),
        val p27: NonNullObject = NonNullObject("27"),
        val p28: NonNullObject = NonNullObject("28"),
        val p29: NonNullObject = NonNullObject("29"),
        val p30: NonNullObject = NonNullObject("30"),
        val p31: NonNullObject = NonNullObject("31")
    )

    @Test
    fun test32() {
        assertThrows<KotlinReflectionInternalError> {
            assertEquals(Dst32(), defaultMapper.readValue<Dst32>("{}"))
            // TODO: #762 is resolved after Kotlin 2.0, so the reason why throw is done is to make CI with Kotlin 2.0 succeed.
            //   After upgrading to Kotlin 2.0, remove exception-related descriptions.
            if (KotlinVersion.CURRENT.major >= 2) throw KotlinReflectionInternalError("")
        }
    }

    data class Dst33(
        val p00: NonNullObject = NonNullObject("0"),
        val p01: NonNullObject = NonNullObject("1"),
        val p02: NonNullObject = NonNullObject("2"),
        val p03: NonNullObject = NonNullObject("3"),
        val p04: NonNullObject = NonNullObject("4"),
        val p05: NonNullObject = NonNullObject("5"),
        val p06: NonNullObject = NonNullObject("6"),
        val p07: NonNullObject = NonNullObject("7"),
        val p08: NonNullObject = NonNullObject("8"),
        val p09: NonNullObject = NonNullObject("9"),
        val p10: NonNullObject = NonNullObject("10"),
        val p11: NonNullObject = NonNullObject("11"),
        val p12: NonNullObject = NonNullObject("12"),
        val p13: NonNullObject = NonNullObject("13"),
        val p14: NonNullObject = NonNullObject("14"),
        val p15: NonNullObject = NonNullObject("15"),
        val p16: NonNullObject = NonNullObject("16"),
        val p17: NonNullObject = NonNullObject("17"),
        val p18: NonNullObject = NonNullObject("18"),
        val p19: NonNullObject = NonNullObject("19"),
        val p20: NonNullObject = NonNullObject("20"),
        val p21: NonNullObject = NonNullObject("21"),
        val p22: NonNullObject = NonNullObject("22"),
        val p23: NonNullObject = NonNullObject("23"),
        val p24: NonNullObject = NonNullObject("24"),
        val p25: NonNullObject = NonNullObject("25"),
        val p26: NonNullObject = NonNullObject("26"),
        val p27: NonNullObject = NonNullObject("27"),
        val p28: NonNullObject = NonNullObject("28"),
        val p29: NonNullObject = NonNullObject("29"),
        val p30: NonNullObject = NonNullObject("30"),
        val p31: NonNullObject = NonNullObject("31"),
        val p32: NonNullObject = NonNullObject("32")
    )

    @Test
    fun test33() {
        assertEquals(Dst33(), defaultMapper.readValue<Dst33>("{}"))
    }

    data class Dst64(
        val p00: NonNullObject = NonNullObject("0"),
        val p01: NonNullObject = NonNullObject("1"),
        val p02: NonNullObject = NonNullObject("2"),
        val p03: NonNullObject = NonNullObject("3"),
        val p04: NonNullObject = NonNullObject("4"),
        val p05: NonNullObject = NonNullObject("5"),
        val p06: NonNullObject = NonNullObject("6"),
        val p07: NonNullObject = NonNullObject("7"),
        val p08: NonNullObject = NonNullObject("8"),
        val p09: NonNullObject = NonNullObject("9"),
        val p10: NonNullObject = NonNullObject("10"),
        val p11: NonNullObject = NonNullObject("11"),
        val p12: NonNullObject = NonNullObject("12"),
        val p13: NonNullObject = NonNullObject("13"),
        val p14: NonNullObject = NonNullObject("14"),
        val p15: NonNullObject = NonNullObject("15"),
        val p16: NonNullObject = NonNullObject("16"),
        val p17: NonNullObject = NonNullObject("17"),
        val p18: NonNullObject = NonNullObject("18"),
        val p19: NonNullObject = NonNullObject("19"),
        val p20: NonNullObject = NonNullObject("20"),
        val p21: NonNullObject = NonNullObject("21"),
        val p22: NonNullObject = NonNullObject("22"),
        val p23: NonNullObject = NonNullObject("23"),
        val p24: NonNullObject = NonNullObject("24"),
        val p25: NonNullObject = NonNullObject("25"),
        val p26: NonNullObject = NonNullObject("26"),
        val p27: NonNullObject = NonNullObject("27"),
        val p28: NonNullObject = NonNullObject("28"),
        val p29: NonNullObject = NonNullObject("29"),
        val p30: NonNullObject = NonNullObject("30"),
        val p31: NonNullObject = NonNullObject("31"),
        val p32: NonNullObject = NonNullObject("32"),
        val p33: NonNullObject = NonNullObject("33"),
        val p34: NonNullObject = NonNullObject("34"),
        val p35: NonNullObject = NonNullObject("35"),
        val p36: NonNullObject = NonNullObject("36"),
        val p37: NonNullObject = NonNullObject("37"),
        val p38: NonNullObject = NonNullObject("38"),
        val p39: NonNullObject = NonNullObject("39"),
        val p40: NonNullObject = NonNullObject("40"),
        val p41: NonNullObject = NonNullObject("41"),
        val p42: NonNullObject = NonNullObject("42"),
        val p43: NonNullObject = NonNullObject("43"),
        val p44: NonNullObject = NonNullObject("44"),
        val p45: NonNullObject = NonNullObject("45"),
        val p46: NonNullObject = NonNullObject("46"),
        val p47: NonNullObject = NonNullObject("47"),
        val p48: NonNullObject = NonNullObject("48"),
        val p49: NonNullObject = NonNullObject("49"),
        val p50: NonNullObject = NonNullObject("50"),
        val p51: NonNullObject = NonNullObject("51"),
        val p52: NonNullObject = NonNullObject("52"),
        val p53: NonNullObject = NonNullObject("53"),
        val p54: NonNullObject = NonNullObject("54"),
        val p55: NonNullObject = NonNullObject("55"),
        val p56: NonNullObject = NonNullObject("56"),
        val p57: NonNullObject = NonNullObject("57"),
        val p58: NonNullObject = NonNullObject("58"),
        val p59: NonNullObject = NonNullObject("59"),
        val p60: NonNullObject = NonNullObject("60"),
        val p61: NonNullObject = NonNullObject("61"),
        val p62: NonNullObject = NonNullObject("62"),
        val p63: NonNullObject = NonNullObject("63")
    )

    @Test
    fun test64() {
        assertThrows<KotlinReflectionInternalError> {
            assertEquals(Dst64(), defaultMapper.readValue<Dst64>("{}"))
            // TODO: #762 is resolved after Kotlin 2.0, so the reason why throw is done is to make CI with Kotlin 2.0 succeed.
            //   After upgrading to Kotlin 2.0, remove exception-related descriptions.
            if (KotlinVersion.CURRENT.major >= 2) throw KotlinReflectionInternalError("")
        }
    }

    data class Dst65(
        val p00: NonNullObject = NonNullObject("0"),
        val p01: NonNullObject = NonNullObject("1"),
        val p02: NonNullObject = NonNullObject("2"),
        val p03: NonNullObject = NonNullObject("3"),
        val p04: NonNullObject = NonNullObject("4"),
        val p05: NonNullObject = NonNullObject("5"),
        val p06: NonNullObject = NonNullObject("6"),
        val p07: NonNullObject = NonNullObject("7"),
        val p08: NonNullObject = NonNullObject("8"),
        val p09: NonNullObject = NonNullObject("9"),
        val p10: NonNullObject = NonNullObject("10"),
        val p11: NonNullObject = NonNullObject("11"),
        val p12: NonNullObject = NonNullObject("12"),
        val p13: NonNullObject = NonNullObject("13"),
        val p14: NonNullObject = NonNullObject("14"),
        val p15: NonNullObject = NonNullObject("15"),
        val p16: NonNullObject = NonNullObject("16"),
        val p17: NonNullObject = NonNullObject("17"),
        val p18: NonNullObject = NonNullObject("18"),
        val p19: NonNullObject = NonNullObject("19"),
        val p20: NonNullObject = NonNullObject("20"),
        val p21: NonNullObject = NonNullObject("21"),
        val p22: NonNullObject = NonNullObject("22"),
        val p23: NonNullObject = NonNullObject("23"),
        val p24: NonNullObject = NonNullObject("24"),
        val p25: NonNullObject = NonNullObject("25"),
        val p26: NonNullObject = NonNullObject("26"),
        val p27: NonNullObject = NonNullObject("27"),
        val p28: NonNullObject = NonNullObject("28"),
        val p29: NonNullObject = NonNullObject("29"),
        val p30: NonNullObject = NonNullObject("30"),
        val p31: NonNullObject = NonNullObject("31"),
        val p32: NonNullObject = NonNullObject("32"),
        val p33: NonNullObject = NonNullObject("33"),
        val p34: NonNullObject = NonNullObject("34"),
        val p35: NonNullObject = NonNullObject("35"),
        val p36: NonNullObject = NonNullObject("36"),
        val p37: NonNullObject = NonNullObject("37"),
        val p38: NonNullObject = NonNullObject("38"),
        val p39: NonNullObject = NonNullObject("39"),
        val p40: NonNullObject = NonNullObject("40"),
        val p41: NonNullObject = NonNullObject("41"),
        val p42: NonNullObject = NonNullObject("42"),
        val p43: NonNullObject = NonNullObject("43"),
        val p44: NonNullObject = NonNullObject("44"),
        val p45: NonNullObject = NonNullObject("45"),
        val p46: NonNullObject = NonNullObject("46"),
        val p47: NonNullObject = NonNullObject("47"),
        val p48: NonNullObject = NonNullObject("48"),
        val p49: NonNullObject = NonNullObject("49"),
        val p50: NonNullObject = NonNullObject("50"),
        val p51: NonNullObject = NonNullObject("51"),
        val p52: NonNullObject = NonNullObject("52"),
        val p53: NonNullObject = NonNullObject("53"),
        val p54: NonNullObject = NonNullObject("54"),
        val p55: NonNullObject = NonNullObject("55"),
        val p56: NonNullObject = NonNullObject("56"),
        val p57: NonNullObject = NonNullObject("57"),
        val p58: NonNullObject = NonNullObject("58"),
        val p59: NonNullObject = NonNullObject("59"),
        val p60: NonNullObject = NonNullObject("60"),
        val p61: NonNullObject = NonNullObject("61"),
        val p62: NonNullObject = NonNullObject("62"),
        val p63: NonNullObject = NonNullObject("63"),
        val p64: NonNullObject = NonNullObject("64")
    )

    @Test
    fun test65() {
        assertEquals(Dst65(), defaultMapper.readValue<Dst65>("{}"))
    }

    // It cannot be a data class because the generated method would exceed the argument size limit.
    class DstMax(
        val p000: NonNullObject = NonNullObject("0"),
        val p001: NonNullObject = NonNullObject("1"),
        val p002: NonNullObject = NonNullObject("2"),
        val p003: NonNullObject = NonNullObject("3"),
        val p004: NonNullObject = NonNullObject("4"),
        val p005: NonNullObject = NonNullObject("5"),
        val p006: NonNullObject = NonNullObject("6"),
        val p007: NonNullObject = NonNullObject("7"),
        val p008: NonNullObject = NonNullObject("8"),
        val p009: NonNullObject = NonNullObject("9"),
        val p010: NonNullObject = NonNullObject("10"),
        val p011: NonNullObject = NonNullObject("11"),
        val p012: NonNullObject = NonNullObject("12"),
        val p013: NonNullObject = NonNullObject("13"),
        val p014: NonNullObject = NonNullObject("14"),
        val p015: NonNullObject = NonNullObject("15"),
        val p016: NonNullObject = NonNullObject("16"),
        val p017: NonNullObject = NonNullObject("17"),
        val p018: NonNullObject = NonNullObject("18"),
        val p019: NonNullObject = NonNullObject("19"),
        val p020: NonNullObject = NonNullObject("20"),
        val p021: NonNullObject = NonNullObject("21"),
        val p022: NonNullObject = NonNullObject("22"),
        val p023: NonNullObject = NonNullObject("23"),
        val p024: NonNullObject = NonNullObject("24"),
        val p025: NonNullObject = NonNullObject("25"),
        val p026: NonNullObject = NonNullObject("26"),
        val p027: NonNullObject = NonNullObject("27"),
        val p028: NonNullObject = NonNullObject("28"),
        val p029: NonNullObject = NonNullObject("29"),
        val p030: NonNullObject = NonNullObject("30"),
        val p031: NonNullObject = NonNullObject("31"),
        val p032: NonNullObject = NonNullObject("32"),
        val p033: NonNullObject = NonNullObject("33"),
        val p034: NonNullObject = NonNullObject("34"),
        val p035: NonNullObject = NonNullObject("35"),
        val p036: NonNullObject = NonNullObject("36"),
        val p037: NonNullObject = NonNullObject("37"),
        val p038: NonNullObject = NonNullObject("38"),
        val p039: NonNullObject = NonNullObject("39"),
        val p040: NonNullObject = NonNullObject("40"),
        val p041: NonNullObject = NonNullObject("41"),
        val p042: NonNullObject = NonNullObject("42"),
        val p043: NonNullObject = NonNullObject("43"),
        val p044: NonNullObject = NonNullObject("44"),
        val p045: NonNullObject = NonNullObject("45"),
        val p046: NonNullObject = NonNullObject("46"),
        val p047: NonNullObject = NonNullObject("47"),
        val p048: NonNullObject = NonNullObject("48"),
        val p049: NonNullObject = NonNullObject("49"),
        val p050: NonNullObject = NonNullObject("50"),
        val p051: NonNullObject = NonNullObject("51"),
        val p052: NonNullObject = NonNullObject("52"),
        val p053: NonNullObject = NonNullObject("53"),
        val p054: NonNullObject = NonNullObject("54"),
        val p055: NonNullObject = NonNullObject("55"),
        val p056: NonNullObject = NonNullObject("56"),
        val p057: NonNullObject = NonNullObject("57"),
        val p058: NonNullObject = NonNullObject("58"),
        val p059: NonNullObject = NonNullObject("59"),
        val p060: NonNullObject = NonNullObject("60"),
        val p061: NonNullObject = NonNullObject("61"),
        val p062: NonNullObject = NonNullObject("62"),
        val p063: NonNullObject = NonNullObject("63"),
        val p064: NonNullObject = NonNullObject("64"),
        val p065: NonNullObject = NonNullObject("65"),
        val p066: NonNullObject = NonNullObject("66"),
        val p067: NonNullObject = NonNullObject("67"),
        val p068: NonNullObject = NonNullObject("68"),
        val p069: NonNullObject = NonNullObject("69"),
        val p070: NonNullObject = NonNullObject("70"),
        val p071: NonNullObject = NonNullObject("71"),
        val p072: NonNullObject = NonNullObject("72"),
        val p073: NonNullObject = NonNullObject("73"),
        val p074: NonNullObject = NonNullObject("74"),
        val p075: NonNullObject = NonNullObject("75"),
        val p076: NonNullObject = NonNullObject("76"),
        val p077: NonNullObject = NonNullObject("77"),
        val p078: NonNullObject = NonNullObject("78"),
        val p079: NonNullObject = NonNullObject("79"),
        val p080: NonNullObject = NonNullObject("80"),
        val p081: NonNullObject = NonNullObject("81"),
        val p082: NonNullObject = NonNullObject("82"),
        val p083: NonNullObject = NonNullObject("83"),
        val p084: NonNullObject = NonNullObject("84"),
        val p085: NonNullObject = NonNullObject("85"),
        val p086: NonNullObject = NonNullObject("86"),
        val p087: NonNullObject = NonNullObject("87"),
        val p088: NonNullObject = NonNullObject("88"),
        val p089: NonNullObject = NonNullObject("89"),
        val p090: NonNullObject = NonNullObject("90"),
        val p091: NonNullObject = NonNullObject("91"),
        val p092: NonNullObject = NonNullObject("92"),
        val p093: NonNullObject = NonNullObject("93"),
        val p094: NonNullObject = NonNullObject("94"),
        val p095: NonNullObject = NonNullObject("95"),
        val p096: NonNullObject = NonNullObject("96"),
        val p097: NonNullObject = NonNullObject("97"),
        val p098: NonNullObject = NonNullObject("98"),
        val p099: NonNullObject = NonNullObject("99"),
        val p100: NonNullObject = NonNullObject("100"),
        val p101: NonNullObject = NonNullObject("101"),
        val p102: NonNullObject = NonNullObject("102"),
        val p103: NonNullObject = NonNullObject("103"),
        val p104: NonNullObject = NonNullObject("104"),
        val p105: NonNullObject = NonNullObject("105"),
        val p106: NonNullObject = NonNullObject("106"),
        val p107: NonNullObject = NonNullObject("107"),
        val p108: NonNullObject = NonNullObject("108"),
        val p109: NonNullObject = NonNullObject("109"),
        val p110: NonNullObject = NonNullObject("110"),
        val p111: NonNullObject = NonNullObject("111"),
        val p112: NonNullObject = NonNullObject("112"),
        val p113: NonNullObject = NonNullObject("113"),
        val p114: NonNullObject = NonNullObject("114"),
        val p115: NonNullObject = NonNullObject("115"),
        val p116: NonNullObject = NonNullObject("116"),
        val p117: NonNullObject = NonNullObject("117"),
        val p118: NonNullObject = NonNullObject("118"),
        val p119: NonNullObject = NonNullObject("119"),
        val p120: NonNullObject = NonNullObject("120"),
        val p121: NonNullObject = NonNullObject("121"),
        val p122: NonNullObject = NonNullObject("122"),
        val p123: NonNullObject = NonNullObject("123"),
        val p124: NonNullObject = NonNullObject("124"),
        val p125: NonNullObject = NonNullObject("125"),
        val p126: NonNullObject = NonNullObject("126"),
        val p127: NonNullObject = NonNullObject("127"),
        val p128: NonNullObject = NonNullObject("128"),
        val p129: NonNullObject = NonNullObject("129"),
        val p130: NonNullObject = NonNullObject("130"),
        val p131: NonNullObject = NonNullObject("131"),
        val p132: NonNullObject = NonNullObject("132"),
        val p133: NonNullObject = NonNullObject("133"),
        val p134: NonNullObject = NonNullObject("134"),
        val p135: NonNullObject = NonNullObject("135"),
        val p136: NonNullObject = NonNullObject("136"),
        val p137: NonNullObject = NonNullObject("137"),
        val p138: NonNullObject = NonNullObject("138"),
        val p139: NonNullObject = NonNullObject("139"),
        val p140: NonNullObject = NonNullObject("140"),
        val p141: NonNullObject = NonNullObject("141"),
        val p142: NonNullObject = NonNullObject("142"),
        val p143: NonNullObject = NonNullObject("143"),
        val p144: NonNullObject = NonNullObject("144"),
        val p145: NonNullObject = NonNullObject("145"),
        val p146: NonNullObject = NonNullObject("146"),
        val p147: NonNullObject = NonNullObject("147"),
        val p148: NonNullObject = NonNullObject("148"),
        val p149: NonNullObject = NonNullObject("149"),
        val p150: NonNullObject = NonNullObject("150"),
        val p151: NonNullObject = NonNullObject("151"),
        val p152: NonNullObject = NonNullObject("152"),
        val p153: NonNullObject = NonNullObject("153"),
        val p154: NonNullObject = NonNullObject("154"),
        val p155: NonNullObject = NonNullObject("155"),
        val p156: NonNullObject = NonNullObject("156"),
        val p157: NonNullObject = NonNullObject("157"),
        val p158: NonNullObject = NonNullObject("158"),
        val p159: NonNullObject = NonNullObject("159"),
        val p160: NonNullObject = NonNullObject("160"),
        val p161: NonNullObject = NonNullObject("161"),
        val p162: NonNullObject = NonNullObject("162"),
        val p163: NonNullObject = NonNullObject("163"),
        val p164: NonNullObject = NonNullObject("164"),
        val p165: NonNullObject = NonNullObject("165"),
        val p166: NonNullObject = NonNullObject("166"),
        val p167: NonNullObject = NonNullObject("167"),
        val p168: NonNullObject = NonNullObject("168"),
        val p169: NonNullObject = NonNullObject("169"),
        val p170: NonNullObject = NonNullObject("170"),
        val p171: NonNullObject = NonNullObject("171"),
        val p172: NonNullObject = NonNullObject("172"),
        val p173: NonNullObject = NonNullObject("173"),
        val p174: NonNullObject = NonNullObject("174"),
        val p175: NonNullObject = NonNullObject("175"),
        val p176: NonNullObject = NonNullObject("176"),
        val p177: NonNullObject = NonNullObject("177"),
        val p178: NonNullObject = NonNullObject("178"),
        val p179: NonNullObject = NonNullObject("179"),
        val p180: NonNullObject = NonNullObject("180"),
        val p181: NonNullObject = NonNullObject("181"),
        val p182: NonNullObject = NonNullObject("182"),
        val p183: NonNullObject = NonNullObject("183"),
        val p184: NonNullObject = NonNullObject("184"),
        val p185: NonNullObject = NonNullObject("185"),
        val p186: NonNullObject = NonNullObject("186"),
        val p187: NonNullObject = NonNullObject("187"),
        val p188: NonNullObject = NonNullObject("188"),
        val p189: NonNullObject = NonNullObject("189"),
        val p190: NonNullObject = NonNullObject("190"),
        val p191: NonNullObject = NonNullObject("191"),
        val p192: NonNullObject = NonNullObject("192"),
        val p193: NonNullObject = NonNullObject("193"),
        val p194: NonNullObject = NonNullObject("194"),
        val p195: NonNullObject = NonNullObject("195"),
        val p196: NonNullObject = NonNullObject("196"),
        val p197: NonNullObject = NonNullObject("197"),
        val p198: NonNullObject = NonNullObject("198"),
        val p199: NonNullObject = NonNullObject("199"),
        val p200: NonNullObject = NonNullObject("200"),
        val p201: NonNullObject = NonNullObject("201"),
        val p202: NonNullObject = NonNullObject("202"),
        val p203: NonNullObject = NonNullObject("203"),
        val p204: NonNullObject = NonNullObject("204"),
        val p205: NonNullObject = NonNullObject("205"),
        val p206: NonNullObject = NonNullObject("206"),
        val p207: NonNullObject = NonNullObject("207"),
        val p208: NonNullObject = NonNullObject("208"),
        val p209: NonNullObject = NonNullObject("209"),
        val p210: NonNullObject = NonNullObject("210"),
        val p211: NonNullObject = NonNullObject("211"),
        val p212: NonNullObject = NonNullObject("212"),
        val p213: NonNullObject = NonNullObject("213"),
        val p214: NonNullObject = NonNullObject("214"),
        val p215: NonNullObject = NonNullObject("215"),
        val p216: NonNullObject = NonNullObject("216"),
        val p217: NonNullObject = NonNullObject("217"),
        val p218: NonNullObject = NonNullObject("218"),
        val p219: NonNullObject = NonNullObject("219"),
        val p220: NonNullObject = NonNullObject("220"),
        val p221: NonNullObject = NonNullObject("221"),
        val p222: NonNullObject = NonNullObject("222"),
        val p223: NonNullObject = NonNullObject("223"),
        val p224: NonNullObject = NonNullObject("224"),
        val p225: NonNullObject = NonNullObject("225"),
        val p226: NonNullObject = NonNullObject("226"),
        val p227: NonNullObject = NonNullObject("227"),
        val p228: NonNullObject = NonNullObject("228"),
        val p229: NonNullObject = NonNullObject("229"),
        val p230: NonNullObject = NonNullObject("230"),
        val p231: NonNullObject = NonNullObject("231"),
        val p232: NonNullObject = NonNullObject("232"),
        val p233: NonNullObject = NonNullObject("233"),
        val p234: NonNullObject = NonNullObject("234"),
        val p235: NonNullObject = NonNullObject("235"),
        val p236: NonNullObject = NonNullObject("236"),
        val p237: NonNullObject = NonNullObject("237"),
        val p238: NonNullObject = NonNullObject("238"),
        val p239: NonNullObject = NonNullObject("239"),
        val p240: NonNullObject = NonNullObject("240"),
        val p241: NonNullObject = NonNullObject("241"),
        val p242: NonNullObject = NonNullObject("242"),
        val p243: NonNullObject = NonNullObject("243"),
        val p244: NonNullObject = NonNullObject("244")
    )

    @Test
    fun testMax() {
        assertReflectEquals(DstMax(), defaultMapper.readValue<DstMax>("{}"))
    }
}
