package tools.jackson.module.kotlin.kogeraIntegration.deser.valueClass.parameterSize.nonNullObject

import com.fasterxml.jackson.annotation.JsonCreator
import tools.jackson.module.kotlin.assertReflectEquals
import tools.jackson.module.kotlin.defaultMapper
import tools.jackson.module.kotlin.readValue
import tools.jackson.module.kotlin.kogeraIntegration.deser.valueClass.NonNullObject
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

/**
 * Up to argument size 32 there is one mask argument for the default argument,
 * 33 ~ 64 there are two, and 65 there are three, so each boundary value is tested.
 * Also, the maximum argument size that can be set in the constructor is 244, so that case is tested as well.
 */
class DeserializeByFactoryWithDefaultArgumentsTest {
    data class Dst32(
        val p00: NonNullObject,
        val p01: NonNullObject,
        val p02: NonNullObject,
        val p03: NonNullObject,
        val p04: NonNullObject,
        val p05: NonNullObject,
        val p06: NonNullObject,
        val p07: NonNullObject,
        val p08: NonNullObject,
        val p09: NonNullObject,
        val p10: NonNullObject,
        val p11: NonNullObject,
        val p12: NonNullObject,
        val p13: NonNullObject,
        val p14: NonNullObject,
        val p15: NonNullObject,
        val p16: NonNullObject,
        val p17: NonNullObject,
        val p18: NonNullObject,
        val p19: NonNullObject,
        val p20: NonNullObject,
        val p21: NonNullObject,
        val p22: NonNullObject,
        val p23: NonNullObject,
        val p24: NonNullObject,
        val p25: NonNullObject,
        val p26: NonNullObject,
        val p27: NonNullObject,
        val p28: NonNullObject,
        val p29: NonNullObject,
        val p30: NonNullObject,
        val p31: NonNullObject
    ) {
        companion object {
            @JvmStatic
            @JsonCreator
            fun creator(
                q00: NonNullObject = NonNullObject("p00"),
                q01: NonNullObject = NonNullObject("p01"),
                q02: NonNullObject = NonNullObject("p02"),
                q03: NonNullObject = NonNullObject("p03"),
                q04: NonNullObject = NonNullObject("p04"),
                q05: NonNullObject = NonNullObject("p05"),
                q06: NonNullObject = NonNullObject("p06"),
                q07: NonNullObject = NonNullObject("p07"),
                q08: NonNullObject = NonNullObject("p08"),
                q09: NonNullObject = NonNullObject("p09"),
                q10: NonNullObject = NonNullObject("p10"),
                q11: NonNullObject = NonNullObject("p11"),
                q12: NonNullObject = NonNullObject("p12"),
                q13: NonNullObject = NonNullObject("p13"),
                q14: NonNullObject = NonNullObject("p14"),
                q15: NonNullObject = NonNullObject("p15"),
                q16: NonNullObject = NonNullObject("p16"),
                q17: NonNullObject = NonNullObject("p17"),
                q18: NonNullObject = NonNullObject("p18"),
                q19: NonNullObject = NonNullObject("p19"),
                q20: NonNullObject = NonNullObject("p20"),
                q21: NonNullObject = NonNullObject("p21"),
                q22: NonNullObject = NonNullObject("p22"),
                q23: NonNullObject = NonNullObject("p23"),
                q24: NonNullObject = NonNullObject("p24"),
                q25: NonNullObject = NonNullObject("p25"),
                q26: NonNullObject = NonNullObject("p26"),
                q27: NonNullObject = NonNullObject("p27"),
                q28: NonNullObject = NonNullObject("p28"),
                q29: NonNullObject = NonNullObject("p29"),
                q30: NonNullObject = NonNullObject("p30"),
                q31: NonNullObject = NonNullObject("p31")
            ) = Dst32(
                q00,
                q01,
                q02,
                q03,
                q04,
                q05,
                q06,
                q07,
                q08,
                q09,
                q10,
                q11,
                q12,
                q13,
                q14,
                q15,
                q16,
                q17,
                q18,
                q19,
                q20,
                q21,
                q22,
                q23,
                q24,
                q25,
                q26,
                q27,
                q28,
                q29,
                q30,
                q31
            )
        }
    }

    @Test
    fun test32() {
        assertEquals(Dst32.creator(), defaultMapper.readValue<Dst32>("{}"))
    }

    data class Dst33(
        val p00: NonNullObject,
        val p01: NonNullObject,
        val p02: NonNullObject,
        val p03: NonNullObject,
        val p04: NonNullObject,
        val p05: NonNullObject,
        val p06: NonNullObject,
        val p07: NonNullObject,
        val p08: NonNullObject,
        val p09: NonNullObject,
        val p10: NonNullObject,
        val p11: NonNullObject,
        val p12: NonNullObject,
        val p13: NonNullObject,
        val p14: NonNullObject,
        val p15: NonNullObject,
        val p16: NonNullObject,
        val p17: NonNullObject,
        val p18: NonNullObject,
        val p19: NonNullObject,
        val p20: NonNullObject,
        val p21: NonNullObject,
        val p22: NonNullObject,
        val p23: NonNullObject,
        val p24: NonNullObject,
        val p25: NonNullObject,
        val p26: NonNullObject,
        val p27: NonNullObject,
        val p28: NonNullObject,
        val p29: NonNullObject,
        val p30: NonNullObject,
        val p31: NonNullObject,
        val p32: NonNullObject
    ) {
        companion object {
            @JvmStatic
            @JsonCreator
            fun creator(
                q00: NonNullObject = NonNullObject("p00"),
                q01: NonNullObject = NonNullObject("p01"),
                q02: NonNullObject = NonNullObject("p02"),
                q03: NonNullObject = NonNullObject("p03"),
                q04: NonNullObject = NonNullObject("p04"),
                q05: NonNullObject = NonNullObject("p05"),
                q06: NonNullObject = NonNullObject("p06"),
                q07: NonNullObject = NonNullObject("p07"),
                q08: NonNullObject = NonNullObject("p08"),
                q09: NonNullObject = NonNullObject("p09"),
                q10: NonNullObject = NonNullObject("p10"),
                q11: NonNullObject = NonNullObject("p11"),
                q12: NonNullObject = NonNullObject("p12"),
                q13: NonNullObject = NonNullObject("p13"),
                q14: NonNullObject = NonNullObject("p14"),
                q15: NonNullObject = NonNullObject("p15"),
                q16: NonNullObject = NonNullObject("p16"),
                q17: NonNullObject = NonNullObject("p17"),
                q18: NonNullObject = NonNullObject("p18"),
                q19: NonNullObject = NonNullObject("p19"),
                q20: NonNullObject = NonNullObject("p20"),
                q21: NonNullObject = NonNullObject("p21"),
                q22: NonNullObject = NonNullObject("p22"),
                q23: NonNullObject = NonNullObject("p23"),
                q24: NonNullObject = NonNullObject("p24"),
                q25: NonNullObject = NonNullObject("p25"),
                q26: NonNullObject = NonNullObject("p26"),
                q27: NonNullObject = NonNullObject("p27"),
                q28: NonNullObject = NonNullObject("p28"),
                q29: NonNullObject = NonNullObject("p29"),
                q30: NonNullObject = NonNullObject("p30"),
                q31: NonNullObject = NonNullObject("p31"),
                q32: NonNullObject = NonNullObject("p32")
            ) = Dst33(
                q00,
                q01,
                q02,
                q03,
                q04,
                q05,
                q06,
                q07,
                q08,
                q09,
                q10,
                q11,
                q12,
                q13,
                q14,
                q15,
                q16,
                q17,
                q18,
                q19,
                q20,
                q21,
                q22,
                q23,
                q24,
                q25,
                q26,
                q27,
                q28,
                q29,
                q30,
                q31,
                q32
            )
        }
    }

    @Test
    fun test33() {
        assertEquals(Dst33.creator(), defaultMapper.readValue<Dst33>("{}"))
    }

    data class Dst64(
        val p00: NonNullObject,
        val p01: NonNullObject,
        val p02: NonNullObject,
        val p03: NonNullObject,
        val p04: NonNullObject,
        val p05: NonNullObject,
        val p06: NonNullObject,
        val p07: NonNullObject,
        val p08: NonNullObject,
        val p09: NonNullObject,
        val p10: NonNullObject,
        val p11: NonNullObject,
        val p12: NonNullObject,
        val p13: NonNullObject,
        val p14: NonNullObject,
        val p15: NonNullObject,
        val p16: NonNullObject,
        val p17: NonNullObject,
        val p18: NonNullObject,
        val p19: NonNullObject,
        val p20: NonNullObject,
        val p21: NonNullObject,
        val p22: NonNullObject,
        val p23: NonNullObject,
        val p24: NonNullObject,
        val p25: NonNullObject,
        val p26: NonNullObject,
        val p27: NonNullObject,
        val p28: NonNullObject,
        val p29: NonNullObject,
        val p30: NonNullObject,
        val p31: NonNullObject,
        val p32: NonNullObject,
        val p33: NonNullObject,
        val p34: NonNullObject,
        val p35: NonNullObject,
        val p36: NonNullObject,
        val p37: NonNullObject,
        val p38: NonNullObject,
        val p39: NonNullObject,
        val p40: NonNullObject,
        val p41: NonNullObject,
        val p42: NonNullObject,
        val p43: NonNullObject,
        val p44: NonNullObject,
        val p45: NonNullObject,
        val p46: NonNullObject,
        val p47: NonNullObject,
        val p48: NonNullObject,
        val p49: NonNullObject,
        val p50: NonNullObject,
        val p51: NonNullObject,
        val p52: NonNullObject,
        val p53: NonNullObject,
        val p54: NonNullObject,
        val p55: NonNullObject,
        val p56: NonNullObject,
        val p57: NonNullObject,
        val p58: NonNullObject,
        val p59: NonNullObject,
        val p60: NonNullObject,
        val p61: NonNullObject,
        val p62: NonNullObject,
        val p63: NonNullObject
    ) {
        companion object {
            @JvmStatic
            @JsonCreator
            fun creator(
                q00: NonNullObject = NonNullObject("p00"),
                q01: NonNullObject = NonNullObject("p01"),
                q02: NonNullObject = NonNullObject("p02"),
                q03: NonNullObject = NonNullObject("p03"),
                q04: NonNullObject = NonNullObject("p04"),
                q05: NonNullObject = NonNullObject("p05"),
                q06: NonNullObject = NonNullObject("p06"),
                q07: NonNullObject = NonNullObject("p07"),
                q08: NonNullObject = NonNullObject("p08"),
                q09: NonNullObject = NonNullObject("p09"),
                q10: NonNullObject = NonNullObject("p10"),
                q11: NonNullObject = NonNullObject("p11"),
                q12: NonNullObject = NonNullObject("p12"),
                q13: NonNullObject = NonNullObject("p13"),
                q14: NonNullObject = NonNullObject("p14"),
                q15: NonNullObject = NonNullObject("p15"),
                q16: NonNullObject = NonNullObject("p16"),
                q17: NonNullObject = NonNullObject("p17"),
                q18: NonNullObject = NonNullObject("p18"),
                q19: NonNullObject = NonNullObject("p19"),
                q20: NonNullObject = NonNullObject("p20"),
                q21: NonNullObject = NonNullObject("p21"),
                q22: NonNullObject = NonNullObject("p22"),
                q23: NonNullObject = NonNullObject("p23"),
                q24: NonNullObject = NonNullObject("p24"),
                q25: NonNullObject = NonNullObject("p25"),
                q26: NonNullObject = NonNullObject("p26"),
                q27: NonNullObject = NonNullObject("p27"),
                q28: NonNullObject = NonNullObject("p28"),
                q29: NonNullObject = NonNullObject("p29"),
                q30: NonNullObject = NonNullObject("p30"),
                q31: NonNullObject = NonNullObject("p31"),
                q32: NonNullObject = NonNullObject("p32"),
                q33: NonNullObject = NonNullObject("p33"),
                q34: NonNullObject = NonNullObject("p34"),
                q35: NonNullObject = NonNullObject("p35"),
                q36: NonNullObject = NonNullObject("p36"),
                q37: NonNullObject = NonNullObject("p37"),
                q38: NonNullObject = NonNullObject("p38"),
                q39: NonNullObject = NonNullObject("p39"),
                q40: NonNullObject = NonNullObject("p40"),
                q41: NonNullObject = NonNullObject("p41"),
                q42: NonNullObject = NonNullObject("p42"),
                q43: NonNullObject = NonNullObject("p43"),
                q44: NonNullObject = NonNullObject("p44"),
                q45: NonNullObject = NonNullObject("p45"),
                q46: NonNullObject = NonNullObject("p46"),
                q47: NonNullObject = NonNullObject("p47"),
                q48: NonNullObject = NonNullObject("p48"),
                q49: NonNullObject = NonNullObject("p49"),
                q50: NonNullObject = NonNullObject("p50"),
                q51: NonNullObject = NonNullObject("p51"),
                q52: NonNullObject = NonNullObject("p52"),
                q53: NonNullObject = NonNullObject("p53"),
                q54: NonNullObject = NonNullObject("p54"),
                q55: NonNullObject = NonNullObject("p55"),
                q56: NonNullObject = NonNullObject("p56"),
                q57: NonNullObject = NonNullObject("p57"),
                q58: NonNullObject = NonNullObject("p58"),
                q59: NonNullObject = NonNullObject("p59"),
                q60: NonNullObject = NonNullObject("p60"),
                q61: NonNullObject = NonNullObject("p61"),
                q62: NonNullObject = NonNullObject("p62"),
                q63: NonNullObject = NonNullObject("p63")
            ) = Dst64(
                q00,
                q01,
                q02,
                q03,
                q04,
                q05,
                q06,
                q07,
                q08,
                q09,
                q10,
                q11,
                q12,
                q13,
                q14,
                q15,
                q16,
                q17,
                q18,
                q19,
                q20,
                q21,
                q22,
                q23,
                q24,
                q25,
                q26,
                q27,
                q28,
                q29,
                q30,
                q31,
                q32,
                q33,
                q34,
                q35,
                q36,
                q37,
                q38,
                q39,
                q40,
                q41,
                q42,
                q43,
                q44,
                q45,
                q46,
                q47,
                q48,
                q49,
                q50,
                q51,
                q52,
                q53,
                q54,
                q55,
                q56,
                q57,
                q58,
                q59,
                q60,
                q61,
                q62,
                q63
            )
        }
    }

    @Test
    fun test64() {
        assertEquals(Dst64.creator(), defaultMapper.readValue<Dst64>("{}"))
    }

    data class Dst65(
        val p00: NonNullObject,
        val p01: NonNullObject,
        val p02: NonNullObject,
        val p03: NonNullObject,
        val p04: NonNullObject,
        val p05: NonNullObject,
        val p06: NonNullObject,
        val p07: NonNullObject,
        val p08: NonNullObject,
        val p09: NonNullObject,
        val p10: NonNullObject,
        val p11: NonNullObject,
        val p12: NonNullObject,
        val p13: NonNullObject,
        val p14: NonNullObject,
        val p15: NonNullObject,
        val p16: NonNullObject,
        val p17: NonNullObject,
        val p18: NonNullObject,
        val p19: NonNullObject,
        val p20: NonNullObject,
        val p21: NonNullObject,
        val p22: NonNullObject,
        val p23: NonNullObject,
        val p24: NonNullObject,
        val p25: NonNullObject,
        val p26: NonNullObject,
        val p27: NonNullObject,
        val p28: NonNullObject,
        val p29: NonNullObject,
        val p30: NonNullObject,
        val p31: NonNullObject,
        val p32: NonNullObject,
        val p33: NonNullObject,
        val p34: NonNullObject,
        val p35: NonNullObject,
        val p36: NonNullObject,
        val p37: NonNullObject,
        val p38: NonNullObject,
        val p39: NonNullObject,
        val p40: NonNullObject,
        val p41: NonNullObject,
        val p42: NonNullObject,
        val p43: NonNullObject,
        val p44: NonNullObject,
        val p45: NonNullObject,
        val p46: NonNullObject,
        val p47: NonNullObject,
        val p48: NonNullObject,
        val p49: NonNullObject,
        val p50: NonNullObject,
        val p51: NonNullObject,
        val p52: NonNullObject,
        val p53: NonNullObject,
        val p54: NonNullObject,
        val p55: NonNullObject,
        val p56: NonNullObject,
        val p57: NonNullObject,
        val p58: NonNullObject,
        val p59: NonNullObject,
        val p60: NonNullObject,
        val p61: NonNullObject,
        val p62: NonNullObject,
        val p63: NonNullObject,
        val p64: NonNullObject
    ) {
        companion object {
            @JvmStatic
            @JsonCreator
            fun creator(
                q00: NonNullObject = NonNullObject("p00"),
                q01: NonNullObject = NonNullObject("p01"),
                q02: NonNullObject = NonNullObject("p02"),
                q03: NonNullObject = NonNullObject("p03"),
                q04: NonNullObject = NonNullObject("p04"),
                q05: NonNullObject = NonNullObject("p05"),
                q06: NonNullObject = NonNullObject("p06"),
                q07: NonNullObject = NonNullObject("p07"),
                q08: NonNullObject = NonNullObject("p08"),
                q09: NonNullObject = NonNullObject("p09"),
                q10: NonNullObject = NonNullObject("p10"),
                q11: NonNullObject = NonNullObject("p11"),
                q12: NonNullObject = NonNullObject("p12"),
                q13: NonNullObject = NonNullObject("p13"),
                q14: NonNullObject = NonNullObject("p14"),
                q15: NonNullObject = NonNullObject("p15"),
                q16: NonNullObject = NonNullObject("p16"),
                q17: NonNullObject = NonNullObject("p17"),
                q18: NonNullObject = NonNullObject("p18"),
                q19: NonNullObject = NonNullObject("p19"),
                q20: NonNullObject = NonNullObject("p20"),
                q21: NonNullObject = NonNullObject("p21"),
                q22: NonNullObject = NonNullObject("p22"),
                q23: NonNullObject = NonNullObject("p23"),
                q24: NonNullObject = NonNullObject("p24"),
                q25: NonNullObject = NonNullObject("p25"),
                q26: NonNullObject = NonNullObject("p26"),
                q27: NonNullObject = NonNullObject("p27"),
                q28: NonNullObject = NonNullObject("p28"),
                q29: NonNullObject = NonNullObject("p29"),
                q30: NonNullObject = NonNullObject("p30"),
                q31: NonNullObject = NonNullObject("p31"),
                q32: NonNullObject = NonNullObject("p32"),
                q33: NonNullObject = NonNullObject("p33"),
                q34: NonNullObject = NonNullObject("p34"),
                q35: NonNullObject = NonNullObject("p35"),
                q36: NonNullObject = NonNullObject("p36"),
                q37: NonNullObject = NonNullObject("p37"),
                q38: NonNullObject = NonNullObject("p38"),
                q39: NonNullObject = NonNullObject("p39"),
                q40: NonNullObject = NonNullObject("p40"),
                q41: NonNullObject = NonNullObject("p41"),
                q42: NonNullObject = NonNullObject("p42"),
                q43: NonNullObject = NonNullObject("p43"),
                q44: NonNullObject = NonNullObject("p44"),
                q45: NonNullObject = NonNullObject("p45"),
                q46: NonNullObject = NonNullObject("p46"),
                q47: NonNullObject = NonNullObject("p47"),
                q48: NonNullObject = NonNullObject("p48"),
                q49: NonNullObject = NonNullObject("p49"),
                q50: NonNullObject = NonNullObject("p50"),
                q51: NonNullObject = NonNullObject("p51"),
                q52: NonNullObject = NonNullObject("p52"),
                q53: NonNullObject = NonNullObject("p53"),
                q54: NonNullObject = NonNullObject("p54"),
                q55: NonNullObject = NonNullObject("p55"),
                q56: NonNullObject = NonNullObject("p56"),
                q57: NonNullObject = NonNullObject("p57"),
                q58: NonNullObject = NonNullObject("p58"),
                q59: NonNullObject = NonNullObject("p59"),
                q60: NonNullObject = NonNullObject("p60"),
                q61: NonNullObject = NonNullObject("p61"),
                q62: NonNullObject = NonNullObject("p62"),
                q63: NonNullObject = NonNullObject("p63"),
                q64: NonNullObject = NonNullObject("p64")
            ) = Dst65(
                q00,
                q01,
                q02,
                q03,
                q04,
                q05,
                q06,
                q07,
                q08,
                q09,
                q10,
                q11,
                q12,
                q13,
                q14,
                q15,
                q16,
                q17,
                q18,
                q19,
                q20,
                q21,
                q22,
                q23,
                q24,
                q25,
                q26,
                q27,
                q28,
                q29,
                q30,
                q31,
                q32,
                q33,
                q34,
                q35,
                q36,
                q37,
                q38,
                q39,
                q40,
                q41,
                q42,
                q43,
                q44,
                q45,
                q46,
                q47,
                q48,
                q49,
                q50,
                q51,
                q52,
                q53,
                q54,
                q55,
                q56,
                q57,
                q58,
                q59,
                q60,
                q61,
                q62,
                q63,
                q64
            )
        }
    }

    @Test
    fun test65() {
        assertEquals(Dst65.creator(), defaultMapper.readValue<Dst65>("{}"))
    }

    // It cannot be a data class because the generated method would exceed the argument size limit.
    class DstMax(
        val p000: NonNullObject,
        val p001: NonNullObject,
        val p002: NonNullObject,
        val p003: NonNullObject,
        val p004: NonNullObject,
        val p005: NonNullObject,
        val p006: NonNullObject,
        val p007: NonNullObject,
        val p008: NonNullObject,
        val p009: NonNullObject,
        val p010: NonNullObject,
        val p011: NonNullObject,
        val p012: NonNullObject,
        val p013: NonNullObject,
        val p014: NonNullObject,
        val p015: NonNullObject,
        val p016: NonNullObject,
        val p017: NonNullObject,
        val p018: NonNullObject,
        val p019: NonNullObject,
        val p020: NonNullObject,
        val p021: NonNullObject,
        val p022: NonNullObject,
        val p023: NonNullObject,
        val p024: NonNullObject,
        val p025: NonNullObject,
        val p026: NonNullObject,
        val p027: NonNullObject,
        val p028: NonNullObject,
        val p029: NonNullObject,
        val p030: NonNullObject,
        val p031: NonNullObject,
        val p032: NonNullObject,
        val p033: NonNullObject,
        val p034: NonNullObject,
        val p035: NonNullObject,
        val p036: NonNullObject,
        val p037: NonNullObject,
        val p038: NonNullObject,
        val p039: NonNullObject,
        val p040: NonNullObject,
        val p041: NonNullObject,
        val p042: NonNullObject,
        val p043: NonNullObject,
        val p044: NonNullObject,
        val p045: NonNullObject,
        val p046: NonNullObject,
        val p047: NonNullObject,
        val p048: NonNullObject,
        val p049: NonNullObject,
        val p050: NonNullObject,
        val p051: NonNullObject,
        val p052: NonNullObject,
        val p053: NonNullObject,
        val p054: NonNullObject,
        val p055: NonNullObject,
        val p056: NonNullObject,
        val p057: NonNullObject,
        val p058: NonNullObject,
        val p059: NonNullObject,
        val p060: NonNullObject,
        val p061: NonNullObject,
        val p062: NonNullObject,
        val p063: NonNullObject,
        val p064: NonNullObject,
        val p065: NonNullObject,
        val p066: NonNullObject,
        val p067: NonNullObject,
        val p068: NonNullObject,
        val p069: NonNullObject,
        val p070: NonNullObject,
        val p071: NonNullObject,
        val p072: NonNullObject,
        val p073: NonNullObject,
        val p074: NonNullObject,
        val p075: NonNullObject,
        val p076: NonNullObject,
        val p077: NonNullObject,
        val p078: NonNullObject,
        val p079: NonNullObject,
        val p080: NonNullObject,
        val p081: NonNullObject,
        val p082: NonNullObject,
        val p083: NonNullObject,
        val p084: NonNullObject,
        val p085: NonNullObject,
        val p086: NonNullObject,
        val p087: NonNullObject,
        val p088: NonNullObject,
        val p089: NonNullObject,
        val p090: NonNullObject,
        val p091: NonNullObject,
        val p092: NonNullObject,
        val p093: NonNullObject,
        val p094: NonNullObject,
        val p095: NonNullObject,
        val p096: NonNullObject,
        val p097: NonNullObject,
        val p098: NonNullObject,
        val p099: NonNullObject,
        val p100: NonNullObject,
        val p101: NonNullObject,
        val p102: NonNullObject,
        val p103: NonNullObject,
        val p104: NonNullObject,
        val p105: NonNullObject,
        val p106: NonNullObject,
        val p107: NonNullObject,
        val p108: NonNullObject,
        val p109: NonNullObject,
        val p110: NonNullObject,
        val p111: NonNullObject,
        val p112: NonNullObject,
        val p113: NonNullObject,
        val p114: NonNullObject,
        val p115: NonNullObject,
        val p116: NonNullObject,
        val p117: NonNullObject,
        val p118: NonNullObject,
        val p119: NonNullObject,
        val p120: NonNullObject,
        val p121: NonNullObject,
        val p122: NonNullObject,
        val p123: NonNullObject,
        val p124: NonNullObject,
        val p125: NonNullObject,
        val p126: NonNullObject,
        val p127: NonNullObject,
        val p128: NonNullObject,
        val p129: NonNullObject,
        val p130: NonNullObject,
        val p131: NonNullObject,
        val p132: NonNullObject,
        val p133: NonNullObject,
        val p134: NonNullObject,
        val p135: NonNullObject,
        val p136: NonNullObject,
        val p137: NonNullObject,
        val p138: NonNullObject,
        val p139: NonNullObject,
        val p140: NonNullObject,
        val p141: NonNullObject,
        val p142: NonNullObject,
        val p143: NonNullObject,
        val p144: NonNullObject,
        val p145: NonNullObject,
        val p146: NonNullObject,
        val p147: NonNullObject,
        val p148: NonNullObject,
        val p149: NonNullObject,
        val p150: NonNullObject,
        val p151: NonNullObject,
        val p152: NonNullObject,
        val p153: NonNullObject,
        val p154: NonNullObject,
        val p155: NonNullObject,
        val p156: NonNullObject,
        val p157: NonNullObject,
        val p158: NonNullObject,
        val p159: NonNullObject,
        val p160: NonNullObject,
        val p161: NonNullObject,
        val p162: NonNullObject,
        val p163: NonNullObject,
        val p164: NonNullObject,
        val p165: NonNullObject,
        val p166: NonNullObject,
        val p167: NonNullObject,
        val p168: NonNullObject,
        val p169: NonNullObject,
        val p170: NonNullObject,
        val p171: NonNullObject,
        val p172: NonNullObject,
        val p173: NonNullObject,
        val p174: NonNullObject,
        val p175: NonNullObject,
        val p176: NonNullObject,
        val p177: NonNullObject,
        val p178: NonNullObject,
        val p179: NonNullObject,
        val p180: NonNullObject,
        val p181: NonNullObject,
        val p182: NonNullObject,
        val p183: NonNullObject,
        val p184: NonNullObject,
        val p185: NonNullObject,
        val p186: NonNullObject,
        val p187: NonNullObject,
        val p188: NonNullObject,
        val p189: NonNullObject,
        val p190: NonNullObject,
        val p191: NonNullObject,
        val p192: NonNullObject,
        val p193: NonNullObject,
        val p194: NonNullObject,
        val p195: NonNullObject,
        val p196: NonNullObject,
        val p197: NonNullObject,
        val p198: NonNullObject,
        val p199: NonNullObject,
        val p200: NonNullObject,
        val p201: NonNullObject,
        val p202: NonNullObject,
        val p203: NonNullObject,
        val p204: NonNullObject,
        val p205: NonNullObject,
        val p206: NonNullObject,
        val p207: NonNullObject,
        val p208: NonNullObject,
        val p209: NonNullObject,
        val p210: NonNullObject,
        val p211: NonNullObject,
        val p212: NonNullObject,
        val p213: NonNullObject,
        val p214: NonNullObject,
        val p215: NonNullObject,
        val p216: NonNullObject,
        val p217: NonNullObject,
        val p218: NonNullObject,
        val p219: NonNullObject,
        val p220: NonNullObject,
        val p221: NonNullObject,
        val p222: NonNullObject,
        val p223: NonNullObject,
        val p224: NonNullObject,
        val p225: NonNullObject,
        val p226: NonNullObject,
        val p227: NonNullObject,
        val p228: NonNullObject,
        val p229: NonNullObject,
        val p230: NonNullObject,
        val p231: NonNullObject,
        val p232: NonNullObject,
        val p233: NonNullObject,
        val p234: NonNullObject,
        val p235: NonNullObject,
        val p236: NonNullObject,
        val p237: NonNullObject,
        val p238: NonNullObject,
        val p239: NonNullObject,
        val p240: NonNullObject,
        val p241: NonNullObject,
        val p242: NonNullObject,
        val p243: NonNullObject
    ) {
        companion object {
            @JvmStatic
            @JsonCreator
            fun creator(
                q000: NonNullObject = NonNullObject("p000"),
                q001: NonNullObject = NonNullObject("p001"),
                q002: NonNullObject = NonNullObject("p002"),
                q003: NonNullObject = NonNullObject("p003"),
                q004: NonNullObject = NonNullObject("p004"),
                q005: NonNullObject = NonNullObject("p005"),
                q006: NonNullObject = NonNullObject("p006"),
                q007: NonNullObject = NonNullObject("p007"),
                q008: NonNullObject = NonNullObject("p008"),
                q009: NonNullObject = NonNullObject("p009"),
                q010: NonNullObject = NonNullObject("p010"),
                q011: NonNullObject = NonNullObject("p011"),
                q012: NonNullObject = NonNullObject("p012"),
                q013: NonNullObject = NonNullObject("p013"),
                q014: NonNullObject = NonNullObject("p014"),
                q015: NonNullObject = NonNullObject("p015"),
                q016: NonNullObject = NonNullObject("p016"),
                q017: NonNullObject = NonNullObject("p017"),
                q018: NonNullObject = NonNullObject("p018"),
                q019: NonNullObject = NonNullObject("p019"),
                q020: NonNullObject = NonNullObject("p020"),
                q021: NonNullObject = NonNullObject("p021"),
                q022: NonNullObject = NonNullObject("p022"),
                q023: NonNullObject = NonNullObject("p023"),
                q024: NonNullObject = NonNullObject("p024"),
                q025: NonNullObject = NonNullObject("p025"),
                q026: NonNullObject = NonNullObject("p026"),
                q027: NonNullObject = NonNullObject("p027"),
                q028: NonNullObject = NonNullObject("p028"),
                q029: NonNullObject = NonNullObject("p029"),
                q030: NonNullObject = NonNullObject("p030"),
                q031: NonNullObject = NonNullObject("p031"),
                q032: NonNullObject = NonNullObject("p032"),
                q033: NonNullObject = NonNullObject("p033"),
                q034: NonNullObject = NonNullObject("p034"),
                q035: NonNullObject = NonNullObject("p035"),
                q036: NonNullObject = NonNullObject("p036"),
                q037: NonNullObject = NonNullObject("p037"),
                q038: NonNullObject = NonNullObject("p038"),
                q039: NonNullObject = NonNullObject("p039"),
                q040: NonNullObject = NonNullObject("p040"),
                q041: NonNullObject = NonNullObject("p041"),
                q042: NonNullObject = NonNullObject("p042"),
                q043: NonNullObject = NonNullObject("p043"),
                q044: NonNullObject = NonNullObject("p044"),
                q045: NonNullObject = NonNullObject("p045"),
                q046: NonNullObject = NonNullObject("p046"),
                q047: NonNullObject = NonNullObject("p047"),
                q048: NonNullObject = NonNullObject("p048"),
                q049: NonNullObject = NonNullObject("p049"),
                q050: NonNullObject = NonNullObject("p050"),
                q051: NonNullObject = NonNullObject("p051"),
                q052: NonNullObject = NonNullObject("p052"),
                q053: NonNullObject = NonNullObject("p053"),
                q054: NonNullObject = NonNullObject("p054"),
                q055: NonNullObject = NonNullObject("p055"),
                q056: NonNullObject = NonNullObject("p056"),
                q057: NonNullObject = NonNullObject("p057"),
                q058: NonNullObject = NonNullObject("p058"),
                q059: NonNullObject = NonNullObject("p059"),
                q060: NonNullObject = NonNullObject("p060"),
                q061: NonNullObject = NonNullObject("p061"),
                q062: NonNullObject = NonNullObject("p062"),
                q063: NonNullObject = NonNullObject("p063"),
                q064: NonNullObject = NonNullObject("p064"),
                q065: NonNullObject = NonNullObject("p065"),
                q066: NonNullObject = NonNullObject("p066"),
                q067: NonNullObject = NonNullObject("p067"),
                q068: NonNullObject = NonNullObject("p068"),
                q069: NonNullObject = NonNullObject("p069"),
                q070: NonNullObject = NonNullObject("p070"),
                q071: NonNullObject = NonNullObject("p071"),
                q072: NonNullObject = NonNullObject("p072"),
                q073: NonNullObject = NonNullObject("p073"),
                q074: NonNullObject = NonNullObject("p074"),
                q075: NonNullObject = NonNullObject("p075"),
                q076: NonNullObject = NonNullObject("p076"),
                q077: NonNullObject = NonNullObject("p077"),
                q078: NonNullObject = NonNullObject("p078"),
                q079: NonNullObject = NonNullObject("p079"),
                q080: NonNullObject = NonNullObject("p080"),
                q081: NonNullObject = NonNullObject("p081"),
                q082: NonNullObject = NonNullObject("p082"),
                q083: NonNullObject = NonNullObject("p083"),
                q084: NonNullObject = NonNullObject("p084"),
                q085: NonNullObject = NonNullObject("p085"),
                q086: NonNullObject = NonNullObject("p086"),
                q087: NonNullObject = NonNullObject("p087"),
                q088: NonNullObject = NonNullObject("p088"),
                q089: NonNullObject = NonNullObject("p089"),
                q090: NonNullObject = NonNullObject("p090"),
                q091: NonNullObject = NonNullObject("p091"),
                q092: NonNullObject = NonNullObject("p092"),
                q093: NonNullObject = NonNullObject("p093"),
                q094: NonNullObject = NonNullObject("p094"),
                q095: NonNullObject = NonNullObject("p095"),
                q096: NonNullObject = NonNullObject("p096"),
                q097: NonNullObject = NonNullObject("p097"),
                q098: NonNullObject = NonNullObject("p098"),
                q099: NonNullObject = NonNullObject("p099"),
                q100: NonNullObject = NonNullObject("p100"),
                q101: NonNullObject = NonNullObject("p101"),
                q102: NonNullObject = NonNullObject("p102"),
                q103: NonNullObject = NonNullObject("p103"),
                q104: NonNullObject = NonNullObject("p104"),
                q105: NonNullObject = NonNullObject("p105"),
                q106: NonNullObject = NonNullObject("p106"),
                q107: NonNullObject = NonNullObject("p107"),
                q108: NonNullObject = NonNullObject("p108"),
                q109: NonNullObject = NonNullObject("p109"),
                q110: NonNullObject = NonNullObject("p110"),
                q111: NonNullObject = NonNullObject("p111"),
                q112: NonNullObject = NonNullObject("p112"),
                q113: NonNullObject = NonNullObject("p113"),
                q114: NonNullObject = NonNullObject("p114"),
                q115: NonNullObject = NonNullObject("p115"),
                q116: NonNullObject = NonNullObject("p116"),
                q117: NonNullObject = NonNullObject("p117"),
                q118: NonNullObject = NonNullObject("p118"),
                q119: NonNullObject = NonNullObject("p119"),
                q120: NonNullObject = NonNullObject("p120"),
                q121: NonNullObject = NonNullObject("p121"),
                q122: NonNullObject = NonNullObject("p122"),
                q123: NonNullObject = NonNullObject("p123"),
                q124: NonNullObject = NonNullObject("p124"),
                q125: NonNullObject = NonNullObject("p125"),
                q126: NonNullObject = NonNullObject("p126"),
                q127: NonNullObject = NonNullObject("p127"),
                q128: NonNullObject = NonNullObject("p128"),
                q129: NonNullObject = NonNullObject("p129"),
                q130: NonNullObject = NonNullObject("p130"),
                q131: NonNullObject = NonNullObject("p131"),
                q132: NonNullObject = NonNullObject("p132"),
                q133: NonNullObject = NonNullObject("p133"),
                q134: NonNullObject = NonNullObject("p134"),
                q135: NonNullObject = NonNullObject("p135"),
                q136: NonNullObject = NonNullObject("p136"),
                q137: NonNullObject = NonNullObject("p137"),
                q138: NonNullObject = NonNullObject("p138"),
                q139: NonNullObject = NonNullObject("p139"),
                q140: NonNullObject = NonNullObject("p140"),
                q141: NonNullObject = NonNullObject("p141"),
                q142: NonNullObject = NonNullObject("p142"),
                q143: NonNullObject = NonNullObject("p143"),
                q144: NonNullObject = NonNullObject("p144"),
                q145: NonNullObject = NonNullObject("p145"),
                q146: NonNullObject = NonNullObject("p146"),
                q147: NonNullObject = NonNullObject("p147"),
                q148: NonNullObject = NonNullObject("p148"),
                q149: NonNullObject = NonNullObject("p149"),
                q150: NonNullObject = NonNullObject("p150"),
                q151: NonNullObject = NonNullObject("p151"),
                q152: NonNullObject = NonNullObject("p152"),
                q153: NonNullObject = NonNullObject("p153"),
                q154: NonNullObject = NonNullObject("p154"),
                q155: NonNullObject = NonNullObject("p155"),
                q156: NonNullObject = NonNullObject("p156"),
                q157: NonNullObject = NonNullObject("p157"),
                q158: NonNullObject = NonNullObject("p158"),
                q159: NonNullObject = NonNullObject("p159"),
                q160: NonNullObject = NonNullObject("p160"),
                q161: NonNullObject = NonNullObject("p161"),
                q162: NonNullObject = NonNullObject("p162"),
                q163: NonNullObject = NonNullObject("p163"),
                q164: NonNullObject = NonNullObject("p164"),
                q165: NonNullObject = NonNullObject("p165"),
                q166: NonNullObject = NonNullObject("p166"),
                q167: NonNullObject = NonNullObject("p167"),
                q168: NonNullObject = NonNullObject("p168"),
                q169: NonNullObject = NonNullObject("p169"),
                q170: NonNullObject = NonNullObject("p170"),
                q171: NonNullObject = NonNullObject("p171"),
                q172: NonNullObject = NonNullObject("p172"),
                q173: NonNullObject = NonNullObject("p173"),
                q174: NonNullObject = NonNullObject("p174"),
                q175: NonNullObject = NonNullObject("p175"),
                q176: NonNullObject = NonNullObject("p176"),
                q177: NonNullObject = NonNullObject("p177"),
                q178: NonNullObject = NonNullObject("p178"),
                q179: NonNullObject = NonNullObject("p179"),
                q180: NonNullObject = NonNullObject("p180"),
                q181: NonNullObject = NonNullObject("p181"),
                q182: NonNullObject = NonNullObject("p182"),
                q183: NonNullObject = NonNullObject("p183"),
                q184: NonNullObject = NonNullObject("p184"),
                q185: NonNullObject = NonNullObject("p185"),
                q186: NonNullObject = NonNullObject("p186"),
                q187: NonNullObject = NonNullObject("p187"),
                q188: NonNullObject = NonNullObject("p188"),
                q189: NonNullObject = NonNullObject("p189"),
                q190: NonNullObject = NonNullObject("p190"),
                q191: NonNullObject = NonNullObject("p191"),
                q192: NonNullObject = NonNullObject("p192"),
                q193: NonNullObject = NonNullObject("p193"),
                q194: NonNullObject = NonNullObject("p194"),
                q195: NonNullObject = NonNullObject("p195"),
                q196: NonNullObject = NonNullObject("p196"),
                q197: NonNullObject = NonNullObject("p197"),
                q198: NonNullObject = NonNullObject("p198"),
                q199: NonNullObject = NonNullObject("p199"),
                q200: NonNullObject = NonNullObject("p200"),
                q201: NonNullObject = NonNullObject("p201"),
                q202: NonNullObject = NonNullObject("p202"),
                q203: NonNullObject = NonNullObject("p203"),
                q204: NonNullObject = NonNullObject("p204"),
                q205: NonNullObject = NonNullObject("p205"),
                q206: NonNullObject = NonNullObject("p206"),
                q207: NonNullObject = NonNullObject("p207"),
                q208: NonNullObject = NonNullObject("p208"),
                q209: NonNullObject = NonNullObject("p209"),
                q210: NonNullObject = NonNullObject("p210"),
                q211: NonNullObject = NonNullObject("p211"),
                q212: NonNullObject = NonNullObject("p212"),
                q213: NonNullObject = NonNullObject("p213"),
                q214: NonNullObject = NonNullObject("p214"),
                q215: NonNullObject = NonNullObject("p215"),
                q216: NonNullObject = NonNullObject("p216"),
                q217: NonNullObject = NonNullObject("p217"),
                q218: NonNullObject = NonNullObject("p218"),
                q219: NonNullObject = NonNullObject("p219"),
                q220: NonNullObject = NonNullObject("p220"),
                q221: NonNullObject = NonNullObject("p221"),
                q222: NonNullObject = NonNullObject("p222"),
                q223: NonNullObject = NonNullObject("p223"),
                q224: NonNullObject = NonNullObject("p224"),
                q225: NonNullObject = NonNullObject("p225"),
                q226: NonNullObject = NonNullObject("p226"),
                q227: NonNullObject = NonNullObject("p227"),
                q228: NonNullObject = NonNullObject("p228"),
                q229: NonNullObject = NonNullObject("p229"),
                q230: NonNullObject = NonNullObject("p230"),
                q231: NonNullObject = NonNullObject("p231"),
                q232: NonNullObject = NonNullObject("p232"),
                q233: NonNullObject = NonNullObject("p233"),
                q234: NonNullObject = NonNullObject("p234"),
                q235: NonNullObject = NonNullObject("p235"),
                q236: NonNullObject = NonNullObject("p236"),
                q237: NonNullObject = NonNullObject("p237"),
                q238: NonNullObject = NonNullObject("p238"),
                q239: NonNullObject = NonNullObject("p239"),
                q240: NonNullObject = NonNullObject("p240"),
                q241: NonNullObject = NonNullObject("p241"),
                q242: NonNullObject = NonNullObject("p242"),
                q243: NonNullObject = NonNullObject("p243")
            ) = DstMax(
                q000,
                q001,
                q002,
                q003,
                q004,
                q005,
                q006,
                q007,
                q008,
                q009,
                q010,
                q011,
                q012,
                q013,
                q014,
                q015,
                q016,
                q017,
                q018,
                q019,
                q020,
                q021,
                q022,
                q023,
                q024,
                q025,
                q026,
                q027,
                q028,
                q029,
                q030,
                q031,
                q032,
                q033,
                q034,
                q035,
                q036,
                q037,
                q038,
                q039,
                q040,
                q041,
                q042,
                q043,
                q044,
                q045,
                q046,
                q047,
                q048,
                q049,
                q050,
                q051,
                q052,
                q053,
                q054,
                q055,
                q056,
                q057,
                q058,
                q059,
                q060,
                q061,
                q062,
                q063,
                q064,
                q065,
                q066,
                q067,
                q068,
                q069,
                q070,
                q071,
                q072,
                q073,
                q074,
                q075,
                q076,
                q077,
                q078,
                q079,
                q080,
                q081,
                q082,
                q083,
                q084,
                q085,
                q086,
                q087,
                q088,
                q089,
                q090,
                q091,
                q092,
                q093,
                q094,
                q095,
                q096,
                q097,
                q098,
                q099,
                q100,
                q101,
                q102,
                q103,
                q104,
                q105,
                q106,
                q107,
                q108,
                q109,
                q110,
                q111,
                q112,
                q113,
                q114,
                q115,
                q116,
                q117,
                q118,
                q119,
                q120,
                q121,
                q122,
                q123,
                q124,
                q125,
                q126,
                q127,
                q128,
                q129,
                q130,
                q131,
                q132,
                q133,
                q134,
                q135,
                q136,
                q137,
                q138,
                q139,
                q140,
                q141,
                q142,
                q143,
                q144,
                q145,
                q146,
                q147,
                q148,
                q149,
                q150,
                q151,
                q152,
                q153,
                q154,
                q155,
                q156,
                q157,
                q158,
                q159,
                q160,
                q161,
                q162,
                q163,
                q164,
                q165,
                q166,
                q167,
                q168,
                q169,
                q170,
                q171,
                q172,
                q173,
                q174,
                q175,
                q176,
                q177,
                q178,
                q179,
                q180,
                q181,
                q182,
                q183,
                q184,
                q185,
                q186,
                q187,
                q188,
                q189,
                q190,
                q191,
                q192,
                q193,
                q194,
                q195,
                q196,
                q197,
                q198,
                q199,
                q200,
                q201,
                q202,
                q203,
                q204,
                q205,
                q206,
                q207,
                q208,
                q209,
                q210,
                q211,
                q212,
                q213,
                q214,
                q215,
                q216,
                q217,
                q218,
                q219,
                q220,
                q221,
                q222,
                q223,
                q224,
                q225,
                q226,
                q227,
                q228,
                q229,
                q230,
                q231,
                q232,
                q233,
                q234,
                q235,
                q236,
                q237,
                q238,
                q239,
                q240,
                q241,
                q242,
                q243
            )
        }
    }

    @Test
    fun testMax() {
        assertReflectEquals(DstMax.creator(), defaultMapper.readValue<DstMax>("{}"))
    }
}
