package tools.jackson.module.kotlin.kogeraIntegration.deser.valueClass.parameterSize.primitive

import com.fasterxml.jackson.annotation.JsonCreator
import tools.jackson.module.kotlin.assertReflectEquals
import tools.jackson.module.kotlin.callPrimaryConstructor
import tools.jackson.module.kotlin.defaultMapper
import tools.jackson.module.kotlin.readValue
import tools.jackson.module.kotlin.kogeraIntegration.deser.valueClass.Primitive
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

// Convert the property p to q (but not the value) to make it an input to the factory function.
private fun replacePQ(src: String) = src.replace(Regex("""p\d+":""")) { "q" + it.value.substring(1) }

/**
 * Up to argument size 32 there is one mask argument for the default argument,
 * 33 ~ 64 there are two, and 65 there are three, so each boundary value is tested.
 * Also, the maximum size of arguments that can be set by a constructor
 * that includes a value class as an argument is 253 (one less by DefaultConstructorMarker), so test that case as well.
 */
class DeserializeByFactoryWithoutDefaultArgumentsTest {
    data class Dst32(
        val p00: Primitive,
        val p01: Primitive,
        val p02: Primitive,
        val p03: Primitive,
        val p04: Primitive,
        val p05: Primitive,
        val p06: Primitive,
        val p07: Primitive,
        val p08: Primitive,
        val p09: Primitive,
        val p10: Primitive,
        val p11: Primitive,
        val p12: Primitive,
        val p13: Primitive,
        val p14: Primitive,
        val p15: Primitive,
        val p16: Primitive,
        val p17: Primitive,
        val p18: Primitive,
        val p19: Primitive,
        val p20: Primitive,
        val p21: Primitive,
        val p22: Primitive,
        val p23: Primitive,
        val p24: Primitive,
        val p25: Primitive,
        val p26: Primitive,
        val p27: Primitive,
        val p28: Primitive,
        val p29: Primitive,
        val p30: Primitive,
        val p31: Primitive
    ) {
        companion object {
            @JvmStatic
            @JsonCreator
            fun creator(
                q00: Primitive,
                q01: Primitive,
                q02: Primitive,
                q03: Primitive,
                q04: Primitive,
                q05: Primitive,
                q06: Primitive,
                q07: Primitive,
                q08: Primitive,
                q09: Primitive,
                q10: Primitive,
                q11: Primitive,
                q12: Primitive,
                q13: Primitive,
                q14: Primitive,
                q15: Primitive,
                q16: Primitive,
                q17: Primitive,
                q18: Primitive,
                q19: Primitive,
                q20: Primitive,
                q21: Primitive,
                q22: Primitive,
                q23: Primitive,
                q24: Primitive,
                q25: Primitive,
                q26: Primitive,
                q27: Primitive,
                q28: Primitive,
                q29: Primitive,
                q30: Primitive,
                q31: Primitive
            ) = Dst32(
                q00,
                q01,
                q02,
                q03,
                q04,
                q05,
                q06,
                q07,
                q08,
                q09,
                q10,
                q11,
                q12,
                q13,
                q14,
                q15,
                q16,
                q17,
                q18,
                q19,
                q20,
                q21,
                q22,
                q23,
                q24,
                q25,
                q26,
                q27,
                q28,
                q29,
                q30,
                q31
            )
        }
    }

    @Test
    fun test32() {
        val expected = callPrimaryConstructor<Dst32> { Primitive(it.index) }
        val src = replacePQ(defaultMapper.writeValueAsString(expected))
        assertEquals(expected, defaultMapper.readValue<Dst32>(src))
    }

    data class Dst33(
        val p00: Primitive,
        val p01: Primitive,
        val p02: Primitive,
        val p03: Primitive,
        val p04: Primitive,
        val p05: Primitive,
        val p06: Primitive,
        val p07: Primitive,
        val p08: Primitive,
        val p09: Primitive,
        val p10: Primitive,
        val p11: Primitive,
        val p12: Primitive,
        val p13: Primitive,
        val p14: Primitive,
        val p15: Primitive,
        val p16: Primitive,
        val p17: Primitive,
        val p18: Primitive,
        val p19: Primitive,
        val p20: Primitive,
        val p21: Primitive,
        val p22: Primitive,
        val p23: Primitive,
        val p24: Primitive,
        val p25: Primitive,
        val p26: Primitive,
        val p27: Primitive,
        val p28: Primitive,
        val p29: Primitive,
        val p30: Primitive,
        val p31: Primitive,
        val p32: Primitive
    ) {
        companion object {
            @JvmStatic
            @JsonCreator
            fun creator(
                q00: Primitive,
                q01: Primitive,
                q02: Primitive,
                q03: Primitive,
                q04: Primitive,
                q05: Primitive,
                q06: Primitive,
                q07: Primitive,
                q08: Primitive,
                q09: Primitive,
                q10: Primitive,
                q11: Primitive,
                q12: Primitive,
                q13: Primitive,
                q14: Primitive,
                q15: Primitive,
                q16: Primitive,
                q17: Primitive,
                q18: Primitive,
                q19: Primitive,
                q20: Primitive,
                q21: Primitive,
                q22: Primitive,
                q23: Primitive,
                q24: Primitive,
                q25: Primitive,
                q26: Primitive,
                q27: Primitive,
                q28: Primitive,
                q29: Primitive,
                q30: Primitive,
                q31: Primitive,
                q32: Primitive
            ) = Dst33(
                q00,
                q01,
                q02,
                q03,
                q04,
                q05,
                q06,
                q07,
                q08,
                q09,
                q10,
                q11,
                q12,
                q13,
                q14,
                q15,
                q16,
                q17,
                q18,
                q19,
                q20,
                q21,
                q22,
                q23,
                q24,
                q25,
                q26,
                q27,
                q28,
                q29,
                q30,
                q31,
                q32
            )
        }
    }

    @Test
    fun test33() {
        val expected = callPrimaryConstructor<Dst33> { Primitive(it.index) }
        val src = replacePQ(defaultMapper.writeValueAsString(expected))
        assertEquals(expected, defaultMapper.readValue<Dst33>(src))
    }

    data class Dst64(
        val p00: Primitive,
        val p01: Primitive,
        val p02: Primitive,
        val p03: Primitive,
        val p04: Primitive,
        val p05: Primitive,
        val p06: Primitive,
        val p07: Primitive,
        val p08: Primitive,
        val p09: Primitive,
        val p10: Primitive,
        val p11: Primitive,
        val p12: Primitive,
        val p13: Primitive,
        val p14: Primitive,
        val p15: Primitive,
        val p16: Primitive,
        val p17: Primitive,
        val p18: Primitive,
        val p19: Primitive,
        val p20: Primitive,
        val p21: Primitive,
        val p22: Primitive,
        val p23: Primitive,
        val p24: Primitive,
        val p25: Primitive,
        val p26: Primitive,
        val p27: Primitive,
        val p28: Primitive,
        val p29: Primitive,
        val p30: Primitive,
        val p31: Primitive,
        val p32: Primitive,
        val p33: Primitive,
        val p34: Primitive,
        val p35: Primitive,
        val p36: Primitive,
        val p37: Primitive,
        val p38: Primitive,
        val p39: Primitive,
        val p40: Primitive,
        val p41: Primitive,
        val p42: Primitive,
        val p43: Primitive,
        val p44: Primitive,
        val p45: Primitive,
        val p46: Primitive,
        val p47: Primitive,
        val p48: Primitive,
        val p49: Primitive,
        val p50: Primitive,
        val p51: Primitive,
        val p52: Primitive,
        val p53: Primitive,
        val p54: Primitive,
        val p55: Primitive,
        val p56: Primitive,
        val p57: Primitive,
        val p58: Primitive,
        val p59: Primitive,
        val p60: Primitive,
        val p61: Primitive,
        val p62: Primitive,
        val p63: Primitive
    ) {
        companion object {
            @JvmStatic
            @JsonCreator
            fun creator(
                q00: Primitive,
                q01: Primitive,
                q02: Primitive,
                q03: Primitive,
                q04: Primitive,
                q05: Primitive,
                q06: Primitive,
                q07: Primitive,
                q08: Primitive,
                q09: Primitive,
                q10: Primitive,
                q11: Primitive,
                q12: Primitive,
                q13: Primitive,
                q14: Primitive,
                q15: Primitive,
                q16: Primitive,
                q17: Primitive,
                q18: Primitive,
                q19: Primitive,
                q20: Primitive,
                q21: Primitive,
                q22: Primitive,
                q23: Primitive,
                q24: Primitive,
                q25: Primitive,
                q26: Primitive,
                q27: Primitive,
                q28: Primitive,
                q29: Primitive,
                q30: Primitive,
                q31: Primitive,
                q32: Primitive,
                q33: Primitive,
                q34: Primitive,
                q35: Primitive,
                q36: Primitive,
                q37: Primitive,
                q38: Primitive,
                q39: Primitive,
                q40: Primitive,
                q41: Primitive,
                q42: Primitive,
                q43: Primitive,
                q44: Primitive,
                q45: Primitive,
                q46: Primitive,
                q47: Primitive,
                q48: Primitive,
                q49: Primitive,
                q50: Primitive,
                q51: Primitive,
                q52: Primitive,
                q53: Primitive,
                q54: Primitive,
                q55: Primitive,
                q56: Primitive,
                q57: Primitive,
                q58: Primitive,
                q59: Primitive,
                q60: Primitive,
                q61: Primitive,
                q62: Primitive,
                q63: Primitive
            ) = Dst64(
                q00,
                q01,
                q02,
                q03,
                q04,
                q05,
                q06,
                q07,
                q08,
                q09,
                q10,
                q11,
                q12,
                q13,
                q14,
                q15,
                q16,
                q17,
                q18,
                q19,
                q20,
                q21,
                q22,
                q23,
                q24,
                q25,
                q26,
                q27,
                q28,
                q29,
                q30,
                q31,
                q32,
                q33,
                q34,
                q35,
                q36,
                q37,
                q38,
                q39,
                q40,
                q41,
                q42,
                q43,
                q44,
                q45,
                q46,
                q47,
                q48,
                q49,
                q50,
                q51,
                q52,
                q53,
                q54,
                q55,
                q56,
                q57,
                q58,
                q59,
                q60,
                q61,
                q62,
                q63
            )
        }
    }

    @Test
    fun test64() {
        val expected = callPrimaryConstructor<Dst64> { Primitive(it.index) }
        val src = replacePQ(defaultMapper.writeValueAsString(expected))
        assertEquals(expected, defaultMapper.readValue<Dst64>(src))
    }

    data class Dst65(
        val p00: Primitive,
        val p01: Primitive,
        val p02: Primitive,
        val p03: Primitive,
        val p04: Primitive,
        val p05: Primitive,
        val p06: Primitive,
        val p07: Primitive,
        val p08: Primitive,
        val p09: Primitive,
        val p10: Primitive,
        val p11: Primitive,
        val p12: Primitive,
        val p13: Primitive,
        val p14: Primitive,
        val p15: Primitive,
        val p16: Primitive,
        val p17: Primitive,
        val p18: Primitive,
        val p19: Primitive,
        val p20: Primitive,
        val p21: Primitive,
        val p22: Primitive,
        val p23: Primitive,
        val p24: Primitive,
        val p25: Primitive,
        val p26: Primitive,
        val p27: Primitive,
        val p28: Primitive,
        val p29: Primitive,
        val p30: Primitive,
        val p31: Primitive,
        val p32: Primitive,
        val p33: Primitive,
        val p34: Primitive,
        val p35: Primitive,
        val p36: Primitive,
        val p37: Primitive,
        val p38: Primitive,
        val p39: Primitive,
        val p40: Primitive,
        val p41: Primitive,
        val p42: Primitive,
        val p43: Primitive,
        val p44: Primitive,
        val p45: Primitive,
        val p46: Primitive,
        val p47: Primitive,
        val p48: Primitive,
        val p49: Primitive,
        val p50: Primitive,
        val p51: Primitive,
        val p52: Primitive,
        val p53: Primitive,
        val p54: Primitive,
        val p55: Primitive,
        val p56: Primitive,
        val p57: Primitive,
        val p58: Primitive,
        val p59: Primitive,
        val p60: Primitive,
        val p61: Primitive,
        val p62: Primitive,
        val p63: Primitive,
        val p64: Primitive
    ) {
        companion object {
            @JvmStatic
            @JsonCreator
            fun creator(
                q00: Primitive,
                q01: Primitive,
                q02: Primitive,
                q03: Primitive,
                q04: Primitive,
                q05: Primitive,
                q06: Primitive,
                q07: Primitive,
                q08: Primitive,
                q09: Primitive,
                q10: Primitive,
                q11: Primitive,
                q12: Primitive,
                q13: Primitive,
                q14: Primitive,
                q15: Primitive,
                q16: Primitive,
                q17: Primitive,
                q18: Primitive,
                q19: Primitive,
                q20: Primitive,
                q21: Primitive,
                q22: Primitive,
                q23: Primitive,
                q24: Primitive,
                q25: Primitive,
                q26: Primitive,
                q27: Primitive,
                q28: Primitive,
                q29: Primitive,
                q30: Primitive,
                q31: Primitive,
                q32: Primitive,
                q33: Primitive,
                q34: Primitive,
                q35: Primitive,
                q36: Primitive,
                q37: Primitive,
                q38: Primitive,
                q39: Primitive,
                q40: Primitive,
                q41: Primitive,
                q42: Primitive,
                q43: Primitive,
                q44: Primitive,
                q45: Primitive,
                q46: Primitive,
                q47: Primitive,
                q48: Primitive,
                q49: Primitive,
                q50: Primitive,
                q51: Primitive,
                q52: Primitive,
                q53: Primitive,
                q54: Primitive,
                q55: Primitive,
                q56: Primitive,
                q57: Primitive,
                q58: Primitive,
                q59: Primitive,
                q60: Primitive,
                q61: Primitive,
                q62: Primitive,
                q63: Primitive,
                q64: Primitive
            ) = Dst65(
                q00,
                q01,
                q02,
                q03,
                q04,
                q05,
                q06,
                q07,
                q08,
                q09,
                q10,
                q11,
                q12,
                q13,
                q14,
                q15,
                q16,
                q17,
                q18,
                q19,
                q20,
                q21,
                q22,
                q23,
                q24,
                q25,
                q26,
                q27,
                q28,
                q29,
                q30,
                q31,
                q32,
                q33,
                q34,
                q35,
                q36,
                q37,
                q38,
                q39,
                q40,
                q41,
                q42,
                q43,
                q44,
                q45,
                q46,
                q47,
                q48,
                q49,
                q50,
                q51,
                q52,
                q53,
                q54,
                q55,
                q56,
                q57,
                q58,
                q59,
                q60,
                q61,
                q62,
                q63,
                q64
            )
        }
    }

    @Test
    fun test65() {
        val expected = callPrimaryConstructor<Dst65> { Primitive(it.index) }
        val src = replacePQ(defaultMapper.writeValueAsString(expected))
        assertEquals(expected, defaultMapper.readValue<Dst65>(src))
    }

    // It cannot be a data class because the generated method would exceed the argument size limit.
    class DstMax(
        val p000: Primitive,
        val p001: Primitive,
        val p002: Primitive,
        val p003: Primitive,
        val p004: Primitive,
        val p005: Primitive,
        val p006: Primitive,
        val p007: Primitive,
        val p008: Primitive,
        val p009: Primitive,
        val p010: Primitive,
        val p011: Primitive,
        val p012: Primitive,
        val p013: Primitive,
        val p014: Primitive,
        val p015: Primitive,
        val p016: Primitive,
        val p017: Primitive,
        val p018: Primitive,
        val p019: Primitive,
        val p020: Primitive,
        val p021: Primitive,
        val p022: Primitive,
        val p023: Primitive,
        val p024: Primitive,
        val p025: Primitive,
        val p026: Primitive,
        val p027: Primitive,
        val p028: Primitive,
        val p029: Primitive,
        val p030: Primitive,
        val p031: Primitive,
        val p032: Primitive,
        val p033: Primitive,
        val p034: Primitive,
        val p035: Primitive,
        val p036: Primitive,
        val p037: Primitive,
        val p038: Primitive,
        val p039: Primitive,
        val p040: Primitive,
        val p041: Primitive,
        val p042: Primitive,
        val p043: Primitive,
        val p044: Primitive,
        val p045: Primitive,
        val p046: Primitive,
        val p047: Primitive,
        val p048: Primitive,
        val p049: Primitive,
        val p050: Primitive,
        val p051: Primitive,
        val p052: Primitive,
        val p053: Primitive,
        val p054: Primitive,
        val p055: Primitive,
        val p056: Primitive,
        val p057: Primitive,
        val p058: Primitive,
        val p059: Primitive,
        val p060: Primitive,
        val p061: Primitive,
        val p062: Primitive,
        val p063: Primitive,
        val p064: Primitive,
        val p065: Primitive,
        val p066: Primitive,
        val p067: Primitive,
        val p068: Primitive,
        val p069: Primitive,
        val p070: Primitive,
        val p071: Primitive,
        val p072: Primitive,
        val p073: Primitive,
        val p074: Primitive,
        val p075: Primitive,
        val p076: Primitive,
        val p077: Primitive,
        val p078: Primitive,
        val p079: Primitive,
        val p080: Primitive,
        val p081: Primitive,
        val p082: Primitive,
        val p083: Primitive,
        val p084: Primitive,
        val p085: Primitive,
        val p086: Primitive,
        val p087: Primitive,
        val p088: Primitive,
        val p089: Primitive,
        val p090: Primitive,
        val p091: Primitive,
        val p092: Primitive,
        val p093: Primitive,
        val p094: Primitive,
        val p095: Primitive,
        val p096: Primitive,
        val p097: Primitive,
        val p098: Primitive,
        val p099: Primitive,
        val p100: Primitive,
        val p101: Primitive,
        val p102: Primitive,
        val p103: Primitive,
        val p104: Primitive,
        val p105: Primitive,
        val p106: Primitive,
        val p107: Primitive,
        val p108: Primitive,
        val p109: Primitive,
        val p110: Primitive,
        val p111: Primitive,
        val p112: Primitive,
        val p113: Primitive,
        val p114: Primitive,
        val p115: Primitive,
        val p116: Primitive,
        val p117: Primitive,
        val p118: Primitive,
        val p119: Primitive,
        val p120: Primitive,
        val p121: Primitive,
        val p122: Primitive,
        val p123: Primitive,
        val p124: Primitive,
        val p125: Primitive,
        val p126: Primitive,
        val p127: Primitive,
        val p128: Primitive,
        val p129: Primitive,
        val p130: Primitive,
        val p131: Primitive,
        val p132: Primitive,
        val p133: Primitive,
        val p134: Primitive,
        val p135: Primitive,
        val p136: Primitive,
        val p137: Primitive,
        val p138: Primitive,
        val p139: Primitive,
        val p140: Primitive,
        val p141: Primitive,
        val p142: Primitive,
        val p143: Primitive,
        val p144: Primitive,
        val p145: Primitive,
        val p146: Primitive,
        val p147: Primitive,
        val p148: Primitive,
        val p149: Primitive,
        val p150: Primitive,
        val p151: Primitive,
        val p152: Primitive,
        val p153: Primitive,
        val p154: Primitive,
        val p155: Primitive,
        val p156: Primitive,
        val p157: Primitive,
        val p158: Primitive,
        val p159: Primitive,
        val p160: Primitive,
        val p161: Primitive,
        val p162: Primitive,
        val p163: Primitive,
        val p164: Primitive,
        val p165: Primitive,
        val p166: Primitive,
        val p167: Primitive,
        val p168: Primitive,
        val p169: Primitive,
        val p170: Primitive,
        val p171: Primitive,
        val p172: Primitive,
        val p173: Primitive,
        val p174: Primitive,
        val p175: Primitive,
        val p176: Primitive,
        val p177: Primitive,
        val p178: Primitive,
        val p179: Primitive,
        val p180: Primitive,
        val p181: Primitive,
        val p182: Primitive,
        val p183: Primitive,
        val p184: Primitive,
        val p185: Primitive,
        val p186: Primitive,
        val p187: Primitive,
        val p188: Primitive,
        val p189: Primitive,
        val p190: Primitive,
        val p191: Primitive,
        val p192: Primitive,
        val p193: Primitive,
        val p194: Primitive,
        val p195: Primitive,
        val p196: Primitive,
        val p197: Primitive,
        val p198: Primitive,
        val p199: Primitive,
        val p200: Primitive,
        val p201: Primitive,
        val p202: Primitive,
        val p203: Primitive,
        val p204: Primitive,
        val p205: Primitive,
        val p206: Primitive,
        val p207: Primitive,
        val p208: Primitive,
        val p209: Primitive,
        val p210: Primitive,
        val p211: Primitive,
        val p212: Primitive,
        val p213: Primitive,
        val p214: Primitive,
        val p215: Primitive,
        val p216: Primitive,
        val p217: Primitive,
        val p218: Primitive,
        val p219: Primitive,
        val p220: Primitive,
        val p221: Primitive,
        val p222: Primitive,
        val p223: Primitive,
        val p224: Primitive,
        val p225: Primitive,
        val p226: Primitive,
        val p227: Primitive,
        val p228: Primitive,
        val p229: Primitive,
        val p230: Primitive,
        val p231: Primitive,
        val p232: Primitive,
        val p233: Primitive,
        val p234: Primitive,
        val p235: Primitive,
        val p236: Primitive,
        val p237: Primitive,
        val p238: Primitive,
        val p239: Primitive,
        val p240: Primitive,
        val p241: Primitive,
        val p242: Primitive,
        val p243: Primitive,
        val p244: Primitive,
        val p245: Primitive,
        val p246: Primitive,
        val p247: Primitive,
        val p248: Primitive,
        val p249: Primitive,
        val p250: Primitive,
        val p251: Primitive,
        val p252: Primitive
    ) {
        companion object {
            @JvmStatic
            @JsonCreator
            fun creator(
                q000: Primitive,
                q001: Primitive,
                q002: Primitive,
                q003: Primitive,
                q004: Primitive,
                q005: Primitive,
                q006: Primitive,
                q007: Primitive,
                q008: Primitive,
                q009: Primitive,
                q010: Primitive,
                q011: Primitive,
                q012: Primitive,
                q013: Primitive,
                q014: Primitive,
                q015: Primitive,
                q016: Primitive,
                q017: Primitive,
                q018: Primitive,
                q019: Primitive,
                q020: Primitive,
                q021: Primitive,
                q022: Primitive,
                q023: Primitive,
                q024: Primitive,
                q025: Primitive,
                q026: Primitive,
                q027: Primitive,
                q028: Primitive,
                q029: Primitive,
                q030: Primitive,
                q031: Primitive,
                q032: Primitive,
                q033: Primitive,
                q034: Primitive,
                q035: Primitive,
                q036: Primitive,
                q037: Primitive,
                q038: Primitive,
                q039: Primitive,
                q040: Primitive,
                q041: Primitive,
                q042: Primitive,
                q043: Primitive,
                q044: Primitive,
                q045: Primitive,
                q046: Primitive,
                q047: Primitive,
                q048: Primitive,
                q049: Primitive,
                q050: Primitive,
                q051: Primitive,
                q052: Primitive,
                q053: Primitive,
                q054: Primitive,
                q055: Primitive,
                q056: Primitive,
                q057: Primitive,
                q058: Primitive,
                q059: Primitive,
                q060: Primitive,
                q061: Primitive,
                q062: Primitive,
                q063: Primitive,
                q064: Primitive,
                q065: Primitive,
                q066: Primitive,
                q067: Primitive,
                q068: Primitive,
                q069: Primitive,
                q070: Primitive,
                q071: Primitive,
                q072: Primitive,
                q073: Primitive,
                q074: Primitive,
                q075: Primitive,
                q076: Primitive,
                q077: Primitive,
                q078: Primitive,
                q079: Primitive,
                q080: Primitive,
                q081: Primitive,
                q082: Primitive,
                q083: Primitive,
                q084: Primitive,
                q085: Primitive,
                q086: Primitive,
                q087: Primitive,
                q088: Primitive,
                q089: Primitive,
                q090: Primitive,
                q091: Primitive,
                q092: Primitive,
                q093: Primitive,
                q094: Primitive,
                q095: Primitive,
                q096: Primitive,
                q097: Primitive,
                q098: Primitive,
                q099: Primitive,
                q100: Primitive,
                q101: Primitive,
                q102: Primitive,
                q103: Primitive,
                q104: Primitive,
                q105: Primitive,
                q106: Primitive,
                q107: Primitive,
                q108: Primitive,
                q109: Primitive,
                q110: Primitive,
                q111: Primitive,
                q112: Primitive,
                q113: Primitive,
                q114: Primitive,
                q115: Primitive,
                q116: Primitive,
                q117: Primitive,
                q118: Primitive,
                q119: Primitive,
                q120: Primitive,
                q121: Primitive,
                q122: Primitive,
                q123: Primitive,
                q124: Primitive,
                q125: Primitive,
                q126: Primitive,
                q127: Primitive,
                q128: Primitive,
                q129: Primitive,
                q130: Primitive,
                q131: Primitive,
                q132: Primitive,
                q133: Primitive,
                q134: Primitive,
                q135: Primitive,
                q136: Primitive,
                q137: Primitive,
                q138: Primitive,
                q139: Primitive,
                q140: Primitive,
                q141: Primitive,
                q142: Primitive,
                q143: Primitive,
                q144: Primitive,
                q145: Primitive,
                q146: Primitive,
                q147: Primitive,
                q148: Primitive,
                q149: Primitive,
                q150: Primitive,
                q151: Primitive,
                q152: Primitive,
                q153: Primitive,
                q154: Primitive,
                q155: Primitive,
                q156: Primitive,
                q157: Primitive,
                q158: Primitive,
                q159: Primitive,
                q160: Primitive,
                q161: Primitive,
                q162: Primitive,
                q163: Primitive,
                q164: Primitive,
                q165: Primitive,
                q166: Primitive,
                q167: Primitive,
                q168: Primitive,
                q169: Primitive,
                q170: Primitive,
                q171: Primitive,
                q172: Primitive,
                q173: Primitive,
                q174: Primitive,
                q175: Primitive,
                q176: Primitive,
                q177: Primitive,
                q178: Primitive,
                q179: Primitive,
                q180: Primitive,
                q181: Primitive,
                q182: Primitive,
                q183: Primitive,
                q184: Primitive,
                q185: Primitive,
                q186: Primitive,
                q187: Primitive,
                q188: Primitive,
                q189: Primitive,
                q190: Primitive,
                q191: Primitive,
                q192: Primitive,
                q193: Primitive,
                q194: Primitive,
                q195: Primitive,
                q196: Primitive,
                q197: Primitive,
                q198: Primitive,
                q199: Primitive,
                q200: Primitive,
                q201: Primitive,
                q202: Primitive,
                q203: Primitive,
                q204: Primitive,
                q205: Primitive,
                q206: Primitive,
                q207: Primitive,
                q208: Primitive,
                q209: Primitive,
                q210: Primitive,
                q211: Primitive,
                q212: Primitive,
                q213: Primitive,
                q214: Primitive,
                q215: Primitive,
                q216: Primitive,
                q217: Primitive,
                q218: Primitive,
                q219: Primitive,
                q220: Primitive,
                q221: Primitive,
                q222: Primitive,
                q223: Primitive,
                q224: Primitive,
                q225: Primitive,
                q226: Primitive,
                q227: Primitive,
                q228: Primitive,
                q229: Primitive,
                q230: Primitive,
                q231: Primitive,
                q232: Primitive,
                q233: Primitive,
                q234: Primitive,
                q235: Primitive,
                q236: Primitive,
                q237: Primitive,
                q238: Primitive,
                q239: Primitive,
                q240: Primitive,
                q241: Primitive,
                q242: Primitive,
                q243: Primitive,
                q244: Primitive,
                q245: Primitive,
                q246: Primitive,
                q247: Primitive,
                q248: Primitive,
                q249: Primitive,
                q250: Primitive,
                q251: Primitive,
                q252: Primitive
            ) = DstMax(
                q000,
                q001,
                q002,
                q003,
                q004,
                q005,
                q006,
                q007,
                q008,
                q009,
                q010,
                q011,
                q012,
                q013,
                q014,
                q015,
                q016,
                q017,
                q018,
                q019,
                q020,
                q021,
                q022,
                q023,
                q024,
                q025,
                q026,
                q027,
                q028,
                q029,
                q030,
                q031,
                q032,
                q033,
                q034,
                q035,
                q036,
                q037,
                q038,
                q039,
                q040,
                q041,
                q042,
                q043,
                q044,
                q045,
                q046,
                q047,
                q048,
                q049,
                q050,
                q051,
                q052,
                q053,
                q054,
                q055,
                q056,
                q057,
                q058,
                q059,
                q060,
                q061,
                q062,
                q063,
                q064,
                q065,
                q066,
                q067,
                q068,
                q069,
                q070,
                q071,
                q072,
                q073,
                q074,
                q075,
                q076,
                q077,
                q078,
                q079,
                q080,
                q081,
                q082,
                q083,
                q084,
                q085,
                q086,
                q087,
                q088,
                q089,
                q090,
                q091,
                q092,
                q093,
                q094,
                q095,
                q096,
                q097,
                q098,
                q099,
                q100,
                q101,
                q102,
                q103,
                q104,
                q105,
                q106,
                q107,
                q108,
                q109,
                q110,
                q111,
                q112,
                q113,
                q114,
                q115,
                q116,
                q117,
                q118,
                q119,
                q120,
                q121,
                q122,
                q123,
                q124,
                q125,
                q126,
                q127,
                q128,
                q129,
                q130,
                q131,
                q132,
                q133,
                q134,
                q135,
                q136,
                q137,
                q138,
                q139,
                q140,
                q141,
                q142,
                q143,
                q144,
                q145,
                q146,
                q147,
                q148,
                q149,
                q150,
                q151,
                q152,
                q153,
                q154,
                q155,
                q156,
                q157,
                q158,
                q159,
                q160,
                q161,
                q162,
                q163,
                q164,
                q165,
                q166,
                q167,
                q168,
                q169,
                q170,
                q171,
                q172,
                q173,
                q174,
                q175,
                q176,
                q177,
                q178,
                q179,
                q180,
                q181,
                q182,
                q183,
                q184,
                q185,
                q186,
                q187,
                q188,
                q189,
                q190,
                q191,
                q192,
                q193,
                q194,
                q195,
                q196,
                q197,
                q198,
                q199,
                q200,
                q201,
                q202,
                q203,
                q204,
                q205,
                q206,
                q207,
                q208,
                q209,
                q210,
                q211,
                q212,
                q213,
                q214,
                q215,
                q216,
                q217,
                q218,
                q219,
                q220,
                q221,
                q222,
                q223,
                q224,
                q225,
                q226,
                q227,
                q228,
                q229,
                q230,
                q231,
                q232,
                q233,
                q234,
                q235,
                q236,
                q237,
                q238,
                q239,
                q240,
                q241,
                q242,
                q243,
                q244,
                q245,
                q246,
                q247,
                q248,
                q249,
                q250,
                q251,
                q252
            )
        }
    }

    @Test
    fun testMax() {
        val expected = callPrimaryConstructor<DstMax> { Primitive(it.index) }
        val src = replacePQ(defaultMapper.writeValueAsString(expected))
        assertReflectEquals(expected, defaultMapper.readValue<DstMax>(src))
    }
}
