name: Build Against Previous Versisons of Kotlin
on:
  push:
    branches:
      - master
      - "3.0"
      - "2.14"
    paths-ignore:
      - "README.md"
      - "release-notes/*"
  pull_request:
    branches:
      - master
      - "3.0"
      - "2.14"
    paths-ignore:
      - "README.md"
      - "release-notes/*"
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        java_version: [ '8', '11', '14' ]
        os: [ 'ubuntu-20.04' ]
        kotlin_compatibility_test: [ 'true', 'false' ]
  steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: "adopt"
        java-version: ${{ matrix.java_version }}
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Execute Gradle build compatibility
      run: ./gradlew build -PcompatibilityTest=${{ matrix.kotlin_compatibility_test }}
