name: Re-build on jackson-databind v3 push
on:
  repository_dispatch:
    types: [jackson-databind-pushed-v3]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java_version: ['17', '21', '25']
        # Versions need to align with ones in 'main.yml' workflow
        kotlin_version: ['2.1.21', '2.2.21', '2.3.0-RC2']
    env:
      JAVA_OPTS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        ref: 3.x
    - name: Set up JDK
      uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5.1.0
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java_version }}
        cache: 'maven'
    - name: Build and test
      run: ./mvnw -B -ff -ntp -Dversion.kotlin=${{ matrix.kotlin_version }} clean verify
