name: Re-build on jackson-databind v2 push
on:
  repository_dispatch:
    types: [jackson-databind-pushed]
  # just for testing
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java_version: ['8', '17', '21', '25']
        # Versions need to align with ones in 'main.yml' workflow
        kotlin_version: ['2.1.21', '2.2.21', '2.3.0-RC2']
    env:
      JAVA_OPTS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        ref: 2.x
    - name: Set up JDK
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java_version }}
        cache: 'maven'
    - name: Build and test
      run: ./mvnw -B -ff -ntp -Dversion.kotlin=${{ matrix.kotlin_version }} clean verify

# No recursive rebuild (yet?)
