name: Re-build on jackson-databind v3 push
on:
  repository_dispatch:
    types: [jackson-databind-pushed-v3]
  # just for testing
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java_version: ['17', '21', '25', '26']
        # Versions need to align with ones in 'main.yml' workflow
        kotlin_version: ['2.2.21', '2.3.21', '2.4.20-RC']
    env:
      JAVA_OPTS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        ref: 3.x
    - name: Set up JDK
      uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java_version }}
        cache: 'maven'
    - name: Build
      # Note: build separately first using default kotlin-core
      run: ./mvnw -B -q -ff -ntp -DskipTests clean package
    - name: Test
      # Note: actual testing should use matrix kotlin-core version (note: MUST specify test phase)
      run: ./mvnw -B -q -ff -ntp -Dversion.kotlin=${{ matrix.kotlin_version }} surefire:test
