name: Build and Deploy Snapshot
on:
  push:
    branches: ['2.*']
    paths-ignore:
    - "README.md"
    - "release-notes/*"
  pull_request:
    paths-ignore:
    - "README.md"
    - "release-notes/*"
  # just for testing
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      java_versions: '["8", "11", "17", "21", "25", "26"]'
      deploy_snapshot: ${{ github.event_name != 'pull_request' }}
    secrets:
      CENTRAL_DEPLOY_USERNAME: ${{ secrets.CENTRAL_DEPLOY_USERNAME }}
      CENTRAL_DEPLOY_PASSWORD: ${{ secrets.CENTRAL_DEPLOY_PASSWORD }}
